// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: hannah/activity_log.proto

package hannahproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActivityLogEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ts             string `protobuf:"bytes,2,opt,name=ts,proto3" json:"ts,omitempty"`
	ChannelType    string `protobuf:"bytes,3,opt,name=channel_type,json=channelType,proto3" json:"channel_type,omitempty"`
	ChannelId      string `protobuf:"bytes,4,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	UserId         int32  `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 0 = unresolved/unset
	RawText        string `protobuf:"bytes,6,opt,name=raw_text,json=rawText,proto3" json:"raw_text,omitempty"`
	IntentName     string `protobuf:"bytes,7,opt,name=intent_name,json=intentName,proto3" json:"intent_name,omitempty"`
	IntentMetaJson string `protobuf:"bytes,8,opt,name=intent_meta_json,json=intentMetaJson,proto3" json:"intent_meta_json,omitempty"` // JSON-encoded, "" = none
	AnswerText     string `protobuf:"bytes,9,opt,name=answer_text,json=answerText,proto3" json:"answer_text,omitempty"`
	HasAudio       bool   `protobuf:"varint,10,opt,name=has_audio,json=hasAudio,proto3" json:"has_audio,omitempty"` // audio_path was set — tells the caller whether to offer playback
}

func (x *ActivityLogEntry) Reset() {
	*x = ActivityLogEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_activity_log_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivityLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityLogEntry) ProtoMessage() {}

func (x *ActivityLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_activity_log_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityLogEntry.ProtoReflect.Descriptor instead.
func (*ActivityLogEntry) Descriptor() ([]byte, []int) {
	return file_hannah_activity_log_proto_rawDescGZIP(), []int{0}
}

func (x *ActivityLogEntry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ActivityLogEntry) GetTs() string {
	if x != nil {
		return x.Ts
	}
	return ""
}

func (x *ActivityLogEntry) GetChannelType() string {
	if x != nil {
		return x.ChannelType
	}
	return ""
}

func (x *ActivityLogEntry) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ActivityLogEntry) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ActivityLogEntry) GetRawText() string {
	if x != nil {
		return x.RawText
	}
	return ""
}

func (x *ActivityLogEntry) GetIntentName() string {
	if x != nil {
		return x.IntentName
	}
	return ""
}

func (x *ActivityLogEntry) GetIntentMetaJson() string {
	if x != nil {
		return x.IntentMetaJson
	}
	return ""
}

func (x *ActivityLogEntry) GetAnswerText() string {
	if x != nil {
		return x.AnswerText
	}
	return ""
}

func (x *ActivityLogEntry) GetHasAudio() bool {
	if x != nil {
		return x.HasAudio
	}
	return false
}

type ListActivityLogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestorId  int32 `protobuf:"varint,1,opt,name=requestor_id,json=requestorId,proto3" json:"requestor_id,omitempty"`
	FilterUserId int32 `protobuf:"varint,2,opt,name=filter_user_id,json=filterUserId,proto3" json:"filter_user_id,omitempty"` // only honored when requestor's trust_level >= 10; 0 = no target filter
	PageSize     int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	BeforeId     int64 `protobuf:"varint,4,opt,name=before_id,json=beforeId,proto3" json:"before_id,omitempty"` // cursor, 0 = start from newest
}

func (x *ListActivityLogRequest) Reset() {
	*x = ListActivityLogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_activity_log_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListActivityLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActivityLogRequest) ProtoMessage() {}

func (x *ListActivityLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_activity_log_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActivityLogRequest.ProtoReflect.Descriptor instead.
func (*ListActivityLogRequest) Descriptor() ([]byte, []int) {
	return file_hannah_activity_log_proto_rawDescGZIP(), []int{1}
}

func (x *ListActivityLogRequest) GetRequestorId() int32 {
	if x != nil {
		return x.RequestorId
	}
	return 0
}

func (x *ListActivityLogRequest) GetFilterUserId() int32 {
	if x != nil {
		return x.FilterUserId
	}
	return 0
}

func (x *ListActivityLogRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListActivityLogRequest) GetBeforeId() int64 {
	if x != nil {
		return x.BeforeId
	}
	return 0
}

type ListActivityLogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*ActivityLogEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	HasMore bool                `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
}

func (x *ListActivityLogResponse) Reset() {
	*x = ListActivityLogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_activity_log_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListActivityLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActivityLogResponse) ProtoMessage() {}

func (x *ListActivityLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_activity_log_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActivityLogResponse.ProtoReflect.Descriptor instead.
func (*ListActivityLogResponse) Descriptor() ([]byte, []int) {
	return file_hannah_activity_log_proto_rawDescGZIP(), []int{2}
}

func (x *ListActivityLogResponse) GetEntries() []*ActivityLogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListActivityLogResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type StreamActivityAudioRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestorId   int32 `protobuf:"varint,1,opt,name=requestor_id,json=requestorId,proto3" json:"requestor_id,omitempty"`
	ActivityLogId int64 `protobuf:"varint,2,opt,name=activity_log_id,json=activityLogId,proto3" json:"activity_log_id,omitempty"`
}

func (x *StreamActivityAudioRequest) Reset() {
	*x = StreamActivityAudioRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_activity_log_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamActivityAudioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamActivityAudioRequest) ProtoMessage() {}

func (x *StreamActivityAudioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_activity_log_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamActivityAudioRequest.ProtoReflect.Descriptor instead.
func (*StreamActivityAudioRequest) Descriptor() ([]byte, []int) {
	return file_hannah_activity_log_proto_rawDescGZIP(), []int{3}
}

func (x *StreamActivityAudioRequest) GetRequestorId() int32 {
	if x != nil {
		return x.RequestorId
	}
	return 0
}

func (x *StreamActivityAudioRequest) GetActivityLogId() int64 {
	if x != nil {
		return x.ActivityLogId
	}
	return 0
}

// A chunk of raw PCM audio (16-bit signed, mono) streamed from a single Activity Log entry.
type ActivityAudioChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pcm        []byte `protobuf:"bytes,1,opt,name=pcm,proto3" json:"pcm,omitempty"`
	SampleRate int32  `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
}

func (x *ActivityAudioChunk) Reset() {
	*x = ActivityAudioChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_activity_log_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivityAudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityAudioChunk) ProtoMessage() {}

func (x *ActivityAudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_activity_log_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityAudioChunk.ProtoReflect.Descriptor instead.
func (*ActivityAudioChunk) Descriptor() ([]byte, []int) {
	return file_hannah_activity_log_proto_rawDescGZIP(), []int{4}
}

func (x *ActivityAudioChunk) GetPcm() []byte {
	if x != nil {
		return x.Pcm
	}
	return nil
}

func (x *ActivityAudioChunk) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

var File_hannah_activity_log_proto protoreflect.FileDescriptor

var file_hannah_activity_log_proto_rawDesc = []byte{
	0x0a, 0x19, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x68, 0x61, 0x6e,
	0x6e, 0x61, 0x68, 0x22, 0xb1, 0x02, 0x0a, 0x10, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x61, 0x77, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x61, 0x77, 0x54, 0x65, 0x78, 0x74, 0x12, 0x1f,
	0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x28, 0x0a, 0x10, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x6a,
	0x73, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x69, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x4d, 0x65, 0x74, 0x61, 0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x54, 0x65, 0x78, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x61,
	0x73, 0x5f, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x68,
	0x61, 0x73, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x22, 0x9b, 0x01, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x5f,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70,
	0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x65, 0x66, 0x6f,
	0x72, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x62, 0x65, 0x66,
	0x6f, 0x72, 0x65, 0x49, 0x64, 0x22, 0x68, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x63, 0x74,
	0x69, 0x76, 0x69, 0x74, 0x79, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x32, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74,
	0x72, 0x69, 0x65, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x68, 0x61, 0x73, 0x5f, 0x6d, 0x6f, 0x72, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68, 0x61, 0x73, 0x4d, 0x6f, 0x72, 0x65, 0x22,
	0x67, 0x0a, 0x1a, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a,
	0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x49, 0x64,
	0x12, 0x26, 0x0a, 0x0f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x5f, 0x6c, 0x6f, 0x67,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x4c, 0x6f, 0x67, 0x49, 0x64, 0x22, 0x47, 0x0a, 0x12, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x10,
	0x0a, 0x03, 0x70, 0x63, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x70, 0x63, 0x6d,
	0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x61, 0x74,
	0x65, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x4e, 0x75, 0x72, 0x50, 0x65, 0x63, 0x68, 0x2f, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2d, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x6f, 0x3b, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hannah_activity_log_proto_rawDescOnce sync.Once
	file_hannah_activity_log_proto_rawDescData = file_hannah_activity_log_proto_rawDesc
)

func file_hannah_activity_log_proto_rawDescGZIP() []byte {
	file_hannah_activity_log_proto_rawDescOnce.Do(func() {
		file_hannah_activity_log_proto_rawDescData = protoimpl.X.CompressGZIP(file_hannah_activity_log_proto_rawDescData)
	})
	return file_hannah_activity_log_proto_rawDescData
}

var file_hannah_activity_log_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_hannah_activity_log_proto_goTypes = []any{
	(*ActivityLogEntry)(nil),           // 0: hannah.ActivityLogEntry
	(*ListActivityLogRequest)(nil),     // 1: hannah.ListActivityLogRequest
	(*ListActivityLogResponse)(nil),    // 2: hannah.ListActivityLogResponse
	(*StreamActivityAudioRequest)(nil), // 3: hannah.StreamActivityAudioRequest
	(*ActivityAudioChunk)(nil),         // 4: hannah.ActivityAudioChunk
}
var file_hannah_activity_log_proto_depIdxs = []int32{
	0, // 0: hannah.ListActivityLogResponse.entries:type_name -> hannah.ActivityLogEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_hannah_activity_log_proto_init() }
func file_hannah_activity_log_proto_init() {
	if File_hannah_activity_log_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hannah_activity_log_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ActivityLogEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_activity_log_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ListActivityLogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_activity_log_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ListActivityLogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_activity_log_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*StreamActivityAudioRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_activity_log_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ActivityAudioChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hannah_activity_log_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hannah_activity_log_proto_goTypes,
		DependencyIndexes: file_hannah_activity_log_proto_depIdxs,
		MessageInfos:      file_hannah_activity_log_proto_msgTypes,
	}.Build()
	File_hannah_activity_log_proto = out.File
	file_hannah_activity_log_proto_rawDesc = nil
	file_hannah_activity_log_proto_goTypes = nil
	file_hannah_activity_log_proto_depIdxs = nil
}
