// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: automation.proto

package hannahproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Sent by an automation service (e.g. telegram_autoresponder) over the AutomationConnect stream.
type AutomationMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*AutomationMessage_Register
	Payload isAutomationMessage_Payload `protobuf_oneof:"payload"`
}

func (x *AutomationMessage) Reset() {
	*x = AutomationMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_automation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AutomationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutomationMessage) ProtoMessage() {}

func (x *AutomationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_automation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutomationMessage.ProtoReflect.Descriptor instead.
func (*AutomationMessage) Descriptor() ([]byte, []int) {
	return file_automation_proto_rawDescGZIP(), []int{0}
}

func (m *AutomationMessage) GetPayload() isAutomationMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *AutomationMessage) GetRegister() *AutomationRegister {
	if x, ok := x.GetPayload().(*AutomationMessage_Register); ok {
		return x.Register
	}
	return nil
}

type isAutomationMessage_Payload interface {
	isAutomationMessage_Payload()
}

type AutomationMessage_Register struct {
	Register *AutomationRegister `protobuf:"bytes,1,opt,name=register,proto3,oneof"` // sent once, right after connecting
}

func (*AutomationMessage_Register) isAutomationMessage_Payload() {}

// Identifies which automation this connection represents.
type AutomationRegister struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Automation string `protobuf:"bytes,1,opt,name=automation,proto3" json:"automation,omitempty"` // e.g. "telegram_autoresponder"
}

func (x *AutomationRegister) Reset() {
	*x = AutomationRegister{}
	if protoimpl.UnsafeEnabled {
		mi := &file_automation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AutomationRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutomationRegister) ProtoMessage() {}

func (x *AutomationRegister) ProtoReflect() protoreflect.Message {
	mi := &file_automation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutomationRegister.ProtoReflect.Descriptor instead.
func (*AutomationRegister) Descriptor() ([]byte, []int) {
	return file_automation_proto_rawDescGZIP(), []int{1}
}

func (x *AutomationRegister) GetAutomation() string {
	if x != nil {
		return x.Automation
	}
	return ""
}

// Sent by Hannah Core over the AutomationConnect stream.
type AutomationCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Command:
	//
	//	*AutomationCommand_Snapshot
	//	*AutomationCommand_StateChanged
	Command isAutomationCommand_Command `protobuf_oneof:"command"`
}

func (x *AutomationCommand) Reset() {
	*x = AutomationCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_automation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AutomationCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutomationCommand) ProtoMessage() {}

func (x *AutomationCommand) ProtoReflect() protoreflect.Message {
	mi := &file_automation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutomationCommand.ProtoReflect.Descriptor instead.
func (*AutomationCommand) Descriptor() ([]byte, []int) {
	return file_automation_proto_rawDescGZIP(), []int{2}
}

func (m *AutomationCommand) GetCommand() isAutomationCommand_Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (x *AutomationCommand) GetSnapshot() *AutomationSnapshot {
	if x, ok := x.GetCommand().(*AutomationCommand_Snapshot); ok {
		return x.Snapshot
	}
	return nil
}

func (x *AutomationCommand) GetStateChanged() *AutomationStateChanged {
	if x, ok := x.GetCommand().(*AutomationCommand_StateChanged); ok {
		return x.StateChanged
	}
	return nil
}

type isAutomationCommand_Command interface {
	isAutomationCommand_Command()
}

type AutomationCommand_Snapshot struct {
	Snapshot *AutomationSnapshot `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof"` // sent once, right after register
}

type AutomationCommand_StateChanged struct {
	StateChanged *AutomationStateChanged `protobuf:"bytes,2,opt,name=state_changed,json=stateChanged,proto3,oneof"` // live delta
}

func (*AutomationCommand_Snapshot) isAutomationCommand_Command() {}

func (*AutomationCommand_StateChanged) isAutomationCommand_Command() {}

// Full list of users with the registered automation currently enabled.
// Sent once per connection, right after AutomationRegister — the recovery
// mechanism for state changes that happened while the service was offline.
type AutomationSnapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserIds []int32 `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
}

func (x *AutomationSnapshot) Reset() {
	*x = AutomationSnapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_automation_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AutomationSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutomationSnapshot) ProtoMessage() {}

func (x *AutomationSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_automation_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutomationSnapshot.ProtoReflect.Descriptor instead.
func (*AutomationSnapshot) Descriptor() ([]byte, []int) {
	return file_automation_proto_rawDescGZIP(), []int{3}
}

func (x *AutomationSnapshot) GetUserIds() []int32 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// A single user's enabled/disabled state changed for the registered automation.
type AutomationStateChanged struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Enabled bool  `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
}

func (x *AutomationStateChanged) Reset() {
	*x = AutomationStateChanged{}
	if protoimpl.UnsafeEnabled {
		mi := &file_automation_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AutomationStateChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutomationStateChanged) ProtoMessage() {}

func (x *AutomationStateChanged) ProtoReflect() protoreflect.Message {
	mi := &file_automation_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutomationStateChanged.ProtoReflect.Descriptor instead.
func (*AutomationStateChanged) Descriptor() ([]byte, []int) {
	return file_automation_proto_rawDescGZIP(), []int{4}
}

func (x *AutomationStateChanged) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AutomationStateChanged) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

var File_automation_proto protoreflect.FileDescriptor

var file_automation_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x75, 0x74, 0x6f, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x22, 0x58, 0x0a, 0x11, 0x41, 0x75,
	0x74, 0x6f, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x38, 0x0a, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x41, 0x75, 0x74, 0x6f, 0x6d,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52,
	0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x22, 0x34, 0x0a, 0x12, 0x41, 0x75, 0x74, 0x6f, 0x6d, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x75,
	0x74, 0x6f, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x61, 0x75, 0x74, 0x6f, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x9f, 0x01, 0x0a, 0x11, 0x41,
	0x75, 0x74, 0x6f, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x12, 0x38, 0x0a, 0x08, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x41, 0x75, 0x74, 0x6f,
	0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x48, 0x00,
	0x52, 0x08, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x45, 0x0a, 0x0d, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x41, 0x75, 0x74, 0x6f, 0x6d,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x64, 0x48, 0x00, 0x52, 0x0c, 0x73, 0x74, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x64, 0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x2f, 0x0a, 0x12,
	0x41, 0x75, 0x74, 0x6f, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x22, 0x4b, 0x0a,
	0x16, 0x41, 0x75, 0x74, 0x6f, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4e, 0x75, 0x72, 0x50, 0x65, 0x63, 0x68,
	0x2f, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x6f,
	0x3b, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_automation_proto_rawDescOnce sync.Once
	file_automation_proto_rawDescData = file_automation_proto_rawDesc
)

func file_automation_proto_rawDescGZIP() []byte {
	file_automation_proto_rawDescOnce.Do(func() {
		file_automation_proto_rawDescData = protoimpl.X.CompressGZIP(file_automation_proto_rawDescData)
	})
	return file_automation_proto_rawDescData
}

var file_automation_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_automation_proto_goTypes = []any{
	(*AutomationMessage)(nil),      // 0: hannah.AutomationMessage
	(*AutomationRegister)(nil),     // 1: hannah.AutomationRegister
	(*AutomationCommand)(nil),      // 2: hannah.AutomationCommand
	(*AutomationSnapshot)(nil),     // 3: hannah.AutomationSnapshot
	(*AutomationStateChanged)(nil), // 4: hannah.AutomationStateChanged
}
var file_automation_proto_depIdxs = []int32{
	1, // 0: hannah.AutomationMessage.register:type_name -> hannah.AutomationRegister
	3, // 1: hannah.AutomationCommand.snapshot:type_name -> hannah.AutomationSnapshot
	4, // 2: hannah.AutomationCommand.state_changed:type_name -> hannah.AutomationStateChanged
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_automation_proto_init() }
func file_automation_proto_init() {
	if File_automation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_automation_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AutomationMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_automation_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AutomationRegister); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_automation_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AutomationCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_automation_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*AutomationSnapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_automation_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*AutomationStateChanged); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_automation_proto_msgTypes[0].OneofWrappers = []any{
		(*AutomationMessage_Register)(nil),
	}
	file_automation_proto_msgTypes[2].OneofWrappers = []any{
		(*AutomationCommand_Snapshot)(nil),
		(*AutomationCommand_StateChanged)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_automation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_automation_proto_goTypes,
		DependencyIndexes: file_automation_proto_depIdxs,
		MessageInfos:      file_automation_proto_msgTypes,
	}.Build()
	File_automation_proto = out.File
	file_automation_proto_rawDesc = nil
	file_automation_proto_goTypes = nil
	file_automation_proto_depIdxs = nil
}
