// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: hannah/channel.proto

package hannahproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RedeemResult int32

const (
	RedeemResult_REDEEM_RESULT_UNSPECIFIED       RedeemResult = 0
	RedeemResult_REDEEM_OK                       RedeemResult = 1
	RedeemResult_REDEEM_UNKNOWN_TOKEN            RedeemResult = 2
	RedeemResult_REDEEM_EXPIRED                  RedeemResult = 3
	RedeemResult_REDEEM_ACCOUNT_LINKED_ELSEWHERE RedeemResult = 4 // account_id already linked to another user
	RedeemResult_REDEEM_ALREADY_LINKED           RedeemResult = 5 // user already has an account linked for this service
)

// Enum value maps for RedeemResult.
var (
	RedeemResult_name = map[int32]string{
		0: "REDEEM_RESULT_UNSPECIFIED",
		1: "REDEEM_OK",
		2: "REDEEM_UNKNOWN_TOKEN",
		3: "REDEEM_EXPIRED",
		4: "REDEEM_ACCOUNT_LINKED_ELSEWHERE",
		5: "REDEEM_ALREADY_LINKED",
	}
	RedeemResult_value = map[string]int32{
		"REDEEM_RESULT_UNSPECIFIED":       0,
		"REDEEM_OK":                       1,
		"REDEEM_UNKNOWN_TOKEN":            2,
		"REDEEM_EXPIRED":                  3,
		"REDEEM_ACCOUNT_LINKED_ELSEWHERE": 4,
		"REDEEM_ALREADY_LINKED":           5,
	}
)

func (x RedeemResult) Enum() *RedeemResult {
	p := new(RedeemResult)
	*p = x
	return p
}

func (x RedeemResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RedeemResult) Descriptor() protoreflect.EnumDescriptor {
	return file_hannah_channel_proto_enumTypes[0].Descriptor()
}

func (RedeemResult) Type() protoreflect.EnumType {
	return &file_hannah_channel_proto_enumTypes[0]
}

func (x RedeemResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RedeemResult.Descriptor instead.
func (RedeemResult) EnumDescriptor() ([]byte, []int) {
	return file_hannah_channel_proto_rawDescGZIP(), []int{0}
}

// Sent by a channel adapter (e.g. the Telegram service) over the ChannelConnect stream.
type ChannelMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//	*ChannelMessage_Register
	//	*ChannelMessage_Redeem
	Payload isChannelMessage_Payload `protobuf_oneof:"payload"`
}

func (x *ChannelMessage) Reset() {
	*x = ChannelMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_channel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChannelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelMessage) ProtoMessage() {}

func (x *ChannelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_channel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelMessage.ProtoReflect.Descriptor instead.
func (*ChannelMessage) Descriptor() ([]byte, []int) {
	return file_hannah_channel_proto_rawDescGZIP(), []int{0}
}

func (m *ChannelMessage) GetPayload() isChannelMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *ChannelMessage) GetRegister() *ChannelRegister {
	if x, ok := x.GetPayload().(*ChannelMessage_Register); ok {
		return x.Register
	}
	return nil
}

func (x *ChannelMessage) GetRedeem() *RedeemLinkToken {
	if x, ok := x.GetPayload().(*ChannelMessage_Redeem); ok {
		return x.Redeem
	}
	return nil
}

type isChannelMessage_Payload interface {
	isChannelMessage_Payload()
}

type ChannelMessage_Register struct {
	Register *ChannelRegister `protobuf:"bytes,1,opt,name=register,proto3,oneof"` // sent once, right after connecting
}

type ChannelMessage_Redeem struct {
	Redeem *RedeemLinkToken `protobuf:"bytes,2,opt,name=redeem,proto3,oneof"` // a user presented a link token to the adapter
}

func (*ChannelMessage_Register) isChannelMessage_Payload() {}

func (*ChannelMessage_Redeem) isChannelMessage_Payload() {}

// Identifies which service this adapter represents. A second adapter registering
// for the same service replaces the first one.
type ChannelRegister struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service     string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`                            // e.g. "telegram" — same key as LinkAccountRequest.service
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"` // e.g. "Telegram"
	// e.g. "https://t.me/HannahBot?start={token}". Empty = service cannot link accounts.
	LinkUrlTemplate string `protobuf:"bytes,3,opt,name=link_url_template,json=linkUrlTemplate,proto3" json:"link_url_template,omitempty"`
	Version         string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"` // adapter version, informational
}

func (x *ChannelRegister) Reset() {
	*x = ChannelRegister{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_channel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChannelRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelRegister) ProtoMessage() {}

func (x *ChannelRegister) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_channel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelRegister.ProtoReflect.Descriptor instead.
func (*ChannelRegister) Descriptor() ([]byte, []int) {
	return file_hannah_channel_proto_rawDescGZIP(), []int{1}
}

func (x *ChannelRegister) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ChannelRegister) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ChannelRegister) GetLinkUrlTemplate() string {
	if x != nil {
		return x.LinkUrlTemplate
	}
	return ""
}

func (x *ChannelRegister) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Redeem a link token issued by CreateLinkToken. The service is implied by the
// registration of the stream it arrives on.
type RedeemLinkToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId       string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // chosen by the adapter, echoed in RedeemLinkTokenResult
	Token           string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	AccountId       string `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`                   // e.g. Telegram user ID
	ProviderPayload string `protobuf:"bytes,4,opt,name=provider_payload,json=providerPayload,proto3" json:"provider_payload,omitempty"` // optional JSON, same semantics as LinkAccountRequest.provider_payload
}

func (x *RedeemLinkToken) Reset() {
	*x = RedeemLinkToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_channel_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RedeemLinkToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedeemLinkToken) ProtoMessage() {}

func (x *RedeemLinkToken) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_channel_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedeemLinkToken.ProtoReflect.Descriptor instead.
func (*RedeemLinkToken) Descriptor() ([]byte, []int) {
	return file_hannah_channel_proto_rawDescGZIP(), []int{2}
}

func (x *RedeemLinkToken) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RedeemLinkToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RedeemLinkToken) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *RedeemLinkToken) GetProviderPayload() string {
	if x != nil {
		return x.ProviderPayload
	}
	return ""
}

// Sent by Hannah Core over the ChannelConnect stream.
type ChannelCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Command:
	//	*ChannelCommand_Registered
	//	*ChannelCommand_RedeemResult
	Command isChannelCommand_Command `protobuf_oneof:"command"`
}

func (x *ChannelCommand) Reset() {
	*x = ChannelCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_channel_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChannelCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelCommand) ProtoMessage() {}

func (x *ChannelCommand) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_channel_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelCommand.ProtoReflect.Descriptor instead.
func (*ChannelCommand) Descriptor() ([]byte, []int) {
	return file_hannah_channel_proto_rawDescGZIP(), []int{3}
}

func (m *ChannelCommand) GetCommand() isChannelCommand_Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (x *ChannelCommand) GetRegistered() *ChannelRegistered {
	if x, ok := x.GetCommand().(*ChannelCommand_Registered); ok {
		return x.Registered
	}
	return nil
}

func (x *ChannelCommand) GetRedeemResult() *RedeemLinkTokenResult {
	if x, ok := x.GetCommand().(*ChannelCommand_RedeemResult); ok {
		return x.RedeemResult
	}
	return nil
}

type isChannelCommand_Command interface {
	isChannelCommand_Command()
}

type ChannelCommand_Registered struct {
	Registered *ChannelRegistered `protobuf:"bytes,1,opt,name=registered,proto3,oneof"` // sent once, right after register
}

type ChannelCommand_RedeemResult struct {
	RedeemResult *RedeemLinkTokenResult `protobuf:"bytes,2,opt,name=redeem_result,json=redeemResult,proto3,oneof"` // answer to RedeemLinkToken
}

func (*ChannelCommand_Registered) isChannelCommand_Command() {}

func (*ChannelCommand_RedeemResult) isChannelCommand_Command() {}

type ChannelRegistered struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChannelRegistered) Reset() {
	*x = ChannelRegistered{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_channel_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChannelRegistered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelRegistered) ProtoMessage() {}

func (x *ChannelRegistered) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_channel_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelRegistered.ProtoReflect.Descriptor instead.
func (*ChannelRegistered) Descriptor() ([]byte, []int) {
	return file_hannah_channel_proto_rawDescGZIP(), []int{4}
}

type RedeemLinkTokenResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId   string       `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // from RedeemLinkToken
	Result      RedeemResult `protobuf:"varint,2,opt,name=result,proto3,enum=hannah.RedeemResult" json:"result,omitempty"`
	UserId      int32        `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`               // set on REDEEM_OK
	DisplayName string       `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"` // set on REDEEM_OK
}

func (x *RedeemLinkTokenResult) Reset() {
	*x = RedeemLinkTokenResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_channel_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RedeemLinkTokenResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedeemLinkTokenResult) ProtoMessage() {}

func (x *RedeemLinkTokenResult) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_channel_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedeemLinkTokenResult.ProtoReflect.Descriptor instead.
func (*RedeemLinkTokenResult) Descriptor() ([]byte, []int) {
	return file_hannah_channel_proto_rawDescGZIP(), []int{5}
}

func (x *RedeemLinkTokenResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RedeemLinkTokenResult) GetResult() RedeemResult {
	if x != nil {
		return x.Result
	}
	return RedeemResult_REDEEM_RESULT_UNSPECIFIED
}

func (x *RedeemLinkTokenResult) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RedeemLinkTokenResult) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

// A currently connected channel adapter.
type ChannelInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service        string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	DisplayName    string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	SupportsLink   bool   `protobuf:"varint,3,opt,name=supports_link,json=supportsLink,proto3" json:"supports_link,omitempty"`       // adapter sent a link_url_template
	ConnectedSince int64  `protobuf:"varint,4,opt,name=connected_since,json=connectedSince,proto3" json:"connected_since,omitempty"` // Unix timestamp (seconds)
}

func (x *ChannelInfo) Reset() {
	*x = ChannelInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_channel_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChannelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelInfo) ProtoMessage() {}

func (x *ChannelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_channel_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelInfo.ProtoReflect.Descriptor instead.
func (*ChannelInfo) Descriptor() ([]byte, []int) {
	return file_hannah_channel_proto_rawDescGZIP(), []int{6}
}

func (x *ChannelInfo) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ChannelInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ChannelInfo) GetSupportsLink() bool {
	if x != nil {
		return x.SupportsLink
	}
	return false
}

func (x *ChannelInfo) GetConnectedSince() int64 {
	if x != nil {
		return x.ConnectedSince
	}
	return 0
}

type GetChannelsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channels []*ChannelInfo `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
}

func (x *GetChannelsResponse) Reset() {
	*x = GetChannelsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_channel_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelsResponse) ProtoMessage() {}

func (x *GetChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_channel_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelsResponse.ProtoReflect.Descriptor instead.
func (*GetChannelsResponse) Descriptor() ([]byte, []int) {
	return file_hannah_channel_proto_rawDescGZIP(), []int{7}
}

func (x *GetChannelsResponse) GetChannels() []*ChannelInfo {
	if x != nil {
		return x.Channels
	}
	return nil
}

var File_hannah_channel_proto protoreflect.FileDescriptor

var file_hannah_channel_proto_rawDesc = []byte{
	0x0a, 0x14, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x22, 0x85,
	0x01, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x35, 0x0a, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x08,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x06, 0x72, 0x65, 0x64, 0x65,
	0x65, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61,
	0x68, 0x2e, 0x52, 0x65, 0x64, 0x65, 0x65, 0x6d, 0x4c, 0x69, 0x6e, 0x6b, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x64, 0x65, 0x65, 0x6d, 0x42, 0x09, 0x0a, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x94, 0x01, 0x0a, 0x0f, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70,
	0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x6c, 0x69, 0x6e, 0x6b, 0x5f,
	0x75, 0x72, 0x6c, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0f, 0x6c, 0x69, 0x6e, 0x6b, 0x55, 0x72, 0x6c, 0x54, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x90, 0x01,
	0x0a, 0x0f, 0x52, 0x65, 0x64, 0x65, 0x65, 0x6d, 0x4c, 0x69, 0x6e, 0x6b, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x10, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x22, 0x9e, 0x01, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x12, 0x3b, 0x0a, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68,
	0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x65, 0x64, 0x48, 0x00, 0x52, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64,
	0x12, 0x44, 0x0a, 0x0d, 0x72, 0x65, 0x64, 0x65, 0x65, 0x6d, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68,
	0x2e, 0x52, 0x65, 0x64, 0x65, 0x65, 0x6d, 0x4c, 0x69, 0x6e, 0x6b, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x0c, 0x72, 0x65, 0x64, 0x65, 0x65, 0x6d,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x22, 0x13, 0x0a, 0x11, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x22, 0xa0, 0x01, 0x0a, 0x15, 0x52, 0x65, 0x64, 0x65, 0x65,
	0x6d, 0x4c, 0x69, 0x6e, 0x6b, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12,
	0x2c, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x14, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x52, 0x65, 0x64, 0x65, 0x65, 0x6d, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61,
	0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69,
	0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x98, 0x01, 0x0a, 0x0b, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c,
	0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72,
	0x74, 0x73, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x73,
	0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x27, 0x0a, 0x0f, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x73, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x53,
	0x69, 0x6e, 0x63, 0x65, 0x22, 0x46, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x08, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x08, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x2a, 0xaa, 0x01, 0x0a,
	0x0c, 0x52, 0x65, 0x64, 0x65, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1d, 0x0a,
	0x19, 0x52, 0x45, 0x44, 0x45, 0x45, 0x4d, 0x5f, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09,
	0x52, 0x45, 0x44, 0x45, 0x45, 0x4d, 0x5f, 0x4f, 0x4b, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x52,
	0x45, 0x44, 0x45, 0x45, 0x4d, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x54, 0x4f,
	0x4b, 0x45, 0x4e, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x45, 0x44, 0x45, 0x45, 0x4d, 0x5f,
	0x45, 0x58, 0x50, 0x49, 0x52, 0x45, 0x44, 0x10, 0x03, 0x12, 0x23, 0x0a, 0x1f, 0x52, 0x45, 0x44,
	0x45, 0x45, 0x4d, 0x5f, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x4c, 0x49, 0x4e, 0x4b,
	0x45, 0x44, 0x5f, 0x45, 0x4c, 0x53, 0x45, 0x57, 0x48, 0x45, 0x52, 0x45, 0x10, 0x04, 0x12, 0x19,
	0x0a, 0x15, 0x52, 0x45, 0x44, 0x45, 0x45, 0x4d, 0x5f, 0x41, 0x4c, 0x52, 0x45, 0x41, 0x44, 0x59,
	0x5f, 0x4c, 0x49, 0x4e, 0x4b, 0x45, 0x44, 0x10, 0x05, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4e, 0x75, 0x72, 0x50, 0x65, 0x63, 0x68, 0x2f,
	0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x6f, 0x3b,
	0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_hannah_channel_proto_rawDescOnce sync.Once
	file_hannah_channel_proto_rawDescData = file_hannah_channel_proto_rawDesc
)

func file_hannah_channel_proto_rawDescGZIP() []byte {
	file_hannah_channel_proto_rawDescOnce.Do(func() {
		file_hannah_channel_proto_rawDescData = protoimpl.X.CompressGZIP(file_hannah_channel_proto_rawDescData)
	})
	return file_hannah_channel_proto_rawDescData
}

var file_hannah_channel_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hannah_channel_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_hannah_channel_proto_goTypes = []any{
	(RedeemResult)(0),             // 0: hannah.RedeemResult
	(*ChannelMessage)(nil),        // 1: hannah.ChannelMessage
	(*ChannelRegister)(nil),       // 2: hannah.ChannelRegister
	(*RedeemLinkToken)(nil),       // 3: hannah.RedeemLinkToken
	(*ChannelCommand)(nil),        // 4: hannah.ChannelCommand
	(*ChannelRegistered)(nil),     // 5: hannah.ChannelRegistered
	(*RedeemLinkTokenResult)(nil), // 6: hannah.RedeemLinkTokenResult
	(*ChannelInfo)(nil),           // 7: hannah.ChannelInfo
	(*GetChannelsResponse)(nil),   // 8: hannah.GetChannelsResponse
}
var file_hannah_channel_proto_depIdxs = []int32{
	2, // 0: hannah.ChannelMessage.register:type_name -> hannah.ChannelRegister
	3, // 1: hannah.ChannelMessage.redeem:type_name -> hannah.RedeemLinkToken
	5, // 2: hannah.ChannelCommand.registered:type_name -> hannah.ChannelRegistered
	6, // 3: hannah.ChannelCommand.redeem_result:type_name -> hannah.RedeemLinkTokenResult
	0, // 4: hannah.RedeemLinkTokenResult.result:type_name -> hannah.RedeemResult
	7, // 5: hannah.GetChannelsResponse.channels:type_name -> hannah.ChannelInfo
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_hannah_channel_proto_init() }
func file_hannah_channel_proto_init() {
	if File_hannah_channel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hannah_channel_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ChannelMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_channel_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ChannelRegister); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_channel_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*RedeemLinkToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_channel_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ChannelCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_channel_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ChannelRegistered); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_channel_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*RedeemLinkTokenResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_channel_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ChannelInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_channel_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetChannelsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_hannah_channel_proto_msgTypes[0].OneofWrappers = []any{
		(*ChannelMessage_Register)(nil),
		(*ChannelMessage_Redeem)(nil),
	}
	file_hannah_channel_proto_msgTypes[3].OneofWrappers = []any{
		(*ChannelCommand_Registered)(nil),
		(*ChannelCommand_RedeemResult)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hannah_channel_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hannah_channel_proto_goTypes,
		DependencyIndexes: file_hannah_channel_proto_depIdxs,
		EnumInfos:         file_hannah_channel_proto_enumTypes,
		MessageInfos:      file_hannah_channel_proto_msgTypes,
	}.Build()
	File_hannah_channel_proto = out.File
	file_hannah_channel_proto_rawDesc = nil
	file_hannah_channel_proto_goTypes = nil
	file_hannah_channel_proto_depIdxs = nil
}
