// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: event_stream.proto

package hannahproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// If empty, subscribe to all event types.
	EventTypes []string `protobuf:"bytes,1,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
}

func (x *EventFilter) Reset() {
	*x = EventFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_stream_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventFilter) ProtoMessage() {}

func (x *EventFilter) ProtoReflect() protoreflect.Message {
	mi := &file_event_stream_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventFilter.ProtoReflect.Descriptor instead.
func (*EventFilter) Descriptor() ([]byte, []int) {
	return file_event_stream_proto_rawDescGZIP(), []int{0}
}

func (x *EventFilter) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

type HannahEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventType string `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "car.parked" | "resident.arrived" | "resident.departed" | "system.notification" | "satellite.firmware"
	Timestamp string `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                  // ISO 8601 UTC
	// Types that are assignable to Payload:
	//
	//	*HannahEvent_CarState
	//	*HannahEvent_ResidentEvent
	//	*HannahEvent_SystemNotification
	//	*HannahEvent_FirmwareEvent
	Payload isHannahEvent_Payload `protobuf_oneof:"payload"`
}

func (x *HannahEvent) Reset() {
	*x = HannahEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_stream_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HannahEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HannahEvent) ProtoMessage() {}

func (x *HannahEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_stream_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HannahEvent.ProtoReflect.Descriptor instead.
func (*HannahEvent) Descriptor() ([]byte, []int) {
	return file_event_stream_proto_rawDescGZIP(), []int{1}
}

func (x *HannahEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *HannahEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (m *HannahEvent) GetPayload() isHannahEvent_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *HannahEvent) GetCarState() *CarStateProto {
	if x, ok := x.GetPayload().(*HannahEvent_CarState); ok {
		return x.CarState
	}
	return nil
}

func (x *HannahEvent) GetResidentEvent() *ResidentEventProto {
	if x, ok := x.GetPayload().(*HannahEvent_ResidentEvent); ok {
		return x.ResidentEvent
	}
	return nil
}

func (x *HannahEvent) GetSystemNotification() *SystemNotificationEvent {
	if x, ok := x.GetPayload().(*HannahEvent_SystemNotification); ok {
		return x.SystemNotification
	}
	return nil
}

func (x *HannahEvent) GetFirmwareEvent() *FirmwareEventProto {
	if x, ok := x.GetPayload().(*HannahEvent_FirmwareEvent); ok {
		return x.FirmwareEvent
	}
	return nil
}

type isHannahEvent_Payload interface {
	isHannahEvent_Payload()
}

type HannahEvent_CarState struct {
	CarState *CarStateProto `protobuf:"bytes,10,opt,name=car_state,json=carState,proto3,oneof"`
}

type HannahEvent_ResidentEvent struct {
	ResidentEvent *ResidentEventProto `protobuf:"bytes,11,opt,name=resident_event,json=residentEvent,proto3,oneof"`
}

type HannahEvent_SystemNotification struct {
	SystemNotification *SystemNotificationEvent `protobuf:"bytes,12,opt,name=system_notification,json=systemNotification,proto3,oneof"`
}

type HannahEvent_FirmwareEvent struct {
	FirmwareEvent *FirmwareEventProto `protobuf:"bytes,13,opt,name=firmware_event,json=firmwareEvent,proto3,oneof"`
}

func (*HannahEvent_CarState) isHannahEvent_Payload() {}

func (*HannahEvent_ResidentEvent) isHannahEvent_Payload() {}

func (*HannahEvent_SystemNotification) isHannahEvent_Payload() {}

func (*HannahEvent_FirmwareEvent) isHannahEvent_Payload() {}

type SystemNotificationEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"` // LLM-reformulierter Benachrichtigungstext
}

func (x *SystemNotificationEvent) Reset() {
	*x = SystemNotificationEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_stream_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemNotificationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemNotificationEvent) ProtoMessage() {}

func (x *SystemNotificationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_stream_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemNotificationEvent.ProtoReflect.Descriptor instead.
func (*SystemNotificationEvent) Descriptor() ([]byte, []int) {
	return file_event_stream_proto_rawDescGZIP(), []int{2}
}

func (x *SystemNotificationEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type FirmwareEventProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Device          string  `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Version         string  `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	UpdateAvailable bool    `protobuf:"varint,3,opt,name=update_available,json=updateAvailable,proto3" json:"update_available,omitempty"`
	NewVersion      *string `protobuf:"bytes,4,opt,name=new_version,json=newVersion,proto3,oneof" json:"new_version,omitempty"`
}

func (x *FirmwareEventProto) Reset() {
	*x = FirmwareEventProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_stream_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FirmwareEventProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirmwareEventProto) ProtoMessage() {}

func (x *FirmwareEventProto) ProtoReflect() protoreflect.Message {
	mi := &file_event_stream_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirmwareEventProto.ProtoReflect.Descriptor instead.
func (*FirmwareEventProto) Descriptor() ([]byte, []int) {
	return file_event_stream_proto_rawDescGZIP(), []int{3}
}

func (x *FirmwareEventProto) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *FirmwareEventProto) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *FirmwareEventProto) GetUpdateAvailable() bool {
	if x != nil {
		return x.UpdateAvailable
	}
	return false
}

func (x *FirmwareEventProto) GetNewVersion() string {
	if x != nil && x.NewVersion != nil {
		return *x.NewVersion
	}
	return ""
}

type TriggerFirmwareUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Device string `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
}

func (x *TriggerFirmwareUpdateRequest) Reset() {
	*x = TriggerFirmwareUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_stream_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TriggerFirmwareUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerFirmwareUpdateRequest) ProtoMessage() {}

func (x *TriggerFirmwareUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_stream_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerFirmwareUpdateRequest.ProtoReflect.Descriptor instead.
func (*TriggerFirmwareUpdateRequest) Descriptor() ([]byte, []int) {
	return file_event_stream_proto_rawDescGZIP(), []int{4}
}

func (x *TriggerFirmwareUpdateRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

type ResidentEventProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomieId    string `protobuf:"bytes,1,opt,name=roomie_id,json=roomieId,proto3" json:"roomie_id,omitempty"`
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Event       string `protobuf:"bytes,3,opt,name=event,proto3" json:"event,omitempty"` // "arrived" | "departed"
}

func (x *ResidentEventProto) Reset() {
	*x = ResidentEventProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_stream_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResidentEventProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResidentEventProto) ProtoMessage() {}

func (x *ResidentEventProto) ProtoReflect() protoreflect.Message {
	mi := &file_event_stream_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResidentEventProto.ProtoReflect.Descriptor instead.
func (*ResidentEventProto) Descriptor() ([]byte, []int) {
	return file_event_stream_proto_rawDescGZIP(), []int{5}
}

func (x *ResidentEventProto) GetRoomieId() string {
	if x != nil {
		return x.RoomieId
	}
	return ""
}

func (x *ResidentEventProto) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ResidentEventProto) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

var File_event_stream_proto protoreflect.FileDescriptor

var file_event_stream_proto_rawDesc = []byte{
	0x0a, 0x12, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x1a, 0x0f, 0x63, 0x61,
	0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a,
	0x0b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x73, 0x22, 0xe9, 0x02,
	0x0a, 0x0b, 0x48, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x34, 0x0a, 0x09, 0x63, 0x61,
	0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x43, 0x61, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x08, 0x63, 0x61, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x43, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x5f, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61,
	0x68, 0x2e, 0x52, 0x65, 0x73, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x52, 0x0a, 0x13, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f,
	0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x53, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x12, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x43, 0x0a, 0x0e, 0x66, 0x69, 0x72,
	0x6d, 0x77, 0x61, 0x72, 0x65, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x0d, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x46, 0x69, 0x72, 0x6d, 0x77,
	0x61, 0x72, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x00, 0x52,
	0x0d, 0x66, 0x69, 0x72, 0x6d, 0x77, 0x61, 0x72, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x09,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x2d, 0x0a, 0x17, 0x53, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0xa7, 0x01, 0x0a, 0x12, 0x46, 0x69, 0x72,
	0x6d, 0x77, 0x61, 0x72, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x16, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x29, 0x0a, 0x10, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x61, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x24, 0x0a, 0x0b,
	0x6e, 0x65, 0x77, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x0a, 0x6e, 0x65, 0x77, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x88,
	0x01, 0x01, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x6e, 0x65, 0x77, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x22, 0x36, 0x0a, 0x1c, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x46, 0x69, 0x72,
	0x6d, 0x77, 0x61, 0x72, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x22, 0x6a, 0x0a, 0x12, 0x52, 0x65,
	0x73, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x65, 0x49, 0x64, 0x12, 0x21, 0x0a,
	0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4e, 0x75, 0x72, 0x50, 0x65, 0x63, 0x68, 0x2f, 0x68, 0x61, 0x6e,
	0x6e, 0x61, 0x68, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x6f, 0x3b, 0x68, 0x61, 0x6e,
	0x6e, 0x61, 0x68, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_event_stream_proto_rawDescOnce sync.Once
	file_event_stream_proto_rawDescData = file_event_stream_proto_rawDesc
)

func file_event_stream_proto_rawDescGZIP() []byte {
	file_event_stream_proto_rawDescOnce.Do(func() {
		file_event_stream_proto_rawDescData = protoimpl.X.CompressGZIP(file_event_stream_proto_rawDescData)
	})
	return file_event_stream_proto_rawDescData
}

var file_event_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_event_stream_proto_goTypes = []any{
	(*EventFilter)(nil),                  // 0: hannah.EventFilter
	(*HannahEvent)(nil),                  // 1: hannah.HannahEvent
	(*SystemNotificationEvent)(nil),      // 2: hannah.SystemNotificationEvent
	(*FirmwareEventProto)(nil),           // 3: hannah.FirmwareEventProto
	(*TriggerFirmwareUpdateRequest)(nil), // 4: hannah.TriggerFirmwareUpdateRequest
	(*ResidentEventProto)(nil),           // 5: hannah.ResidentEventProto
	(*CarStateProto)(nil),                // 6: hannah.CarStateProto
}
var file_event_stream_proto_depIdxs = []int32{
	6, // 0: hannah.HannahEvent.car_state:type_name -> hannah.CarStateProto
	5, // 1: hannah.HannahEvent.resident_event:type_name -> hannah.ResidentEventProto
	2, // 2: hannah.HannahEvent.system_notification:type_name -> hannah.SystemNotificationEvent
	3, // 3: hannah.HannahEvent.firmware_event:type_name -> hannah.FirmwareEventProto
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_event_stream_proto_init() }
func file_event_stream_proto_init() {
	if File_event_stream_proto != nil {
		return
	}
	file_car_state_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_event_stream_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*EventFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_stream_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*HannahEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_stream_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SystemNotificationEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_stream_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*FirmwareEventProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_stream_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*TriggerFirmwareUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_stream_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ResidentEventProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_event_stream_proto_msgTypes[1].OneofWrappers = []any{
		(*HannahEvent_CarState)(nil),
		(*HannahEvent_ResidentEvent)(nil),
		(*HannahEvent_SystemNotification)(nil),
		(*HannahEvent_FirmwareEvent)(nil),
	}
	file_event_stream_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_event_stream_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_stream_proto_goTypes,
		DependencyIndexes: file_event_stream_proto_depIdxs,
		MessageInfos:      file_event_stream_proto_msgTypes,
	}.Build()
	File_event_stream_proto = out.File
	file_event_stream_proto_rawDesc = nil
	file_event_stream_proto_goTypes = nil
	file_event_stream_proto_depIdxs = nil
}
