// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: hannah/infrastructure.proto

package hannahproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Infrastructure services that Hannah Core announces to all connected components
// (service discovery). Typed on purpose — a new kind of service gets a new enum value,
// a fundamentally new use case gets its own oneof branch, never a generic key/value bag.
type ServiceKind int32

const (
	ServiceKind_SERVICE_KIND_UNSPECIFIED   ServiceKind = 0
	ServiceKind_SERVICE_KIND_LOG_COLLECTOR ServiceKind = 1
)

// Enum value maps for ServiceKind.
var (
	ServiceKind_name = map[int32]string{
		0: "SERVICE_KIND_UNSPECIFIED",
		1: "SERVICE_KIND_LOG_COLLECTOR",
	}
	ServiceKind_value = map[string]int32{
		"SERVICE_KIND_UNSPECIFIED":   0,
		"SERVICE_KIND_LOG_COLLECTOR": 1,
	}
)

func (x ServiceKind) Enum() *ServiceKind {
	p := new(ServiceKind)
	*p = x
	return p
}

func (x ServiceKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceKind) Descriptor() protoreflect.EnumDescriptor {
	return file_hannah_infrastructure_proto_enumTypes[0].Descriptor()
}

func (ServiceKind) Type() protoreflect.EnumType {
	return &file_hannah_infrastructure_proto_enumTypes[0]
}

func (x ServiceKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceKind.Descriptor instead.
func (ServiceKind) EnumDescriptor() ([]byte, []int) {
	return file_hannah_infrastructure_proto_rawDescGZIP(), []int{0}
}

// Where a currently available infrastructure service can be reached.
type ServiceEndpoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind     ServiceKind `protobuf:"varint,1,opt,name=kind,proto3,enum=hannah.ServiceKind" json:"kind,omitempty"`
	Instance string      `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	Host     string      `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port     int32       `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Version  string      `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"` // informational
}

func (x *ServiceEndpoint) Reset() {
	*x = ServiceEndpoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_infrastructure_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceEndpoint) ProtoMessage() {}

func (x *ServiceEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_infrastructure_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceEndpoint.ProtoReflect.Descriptor instead.
func (*ServiceEndpoint) Descriptor() ([]byte, []int) {
	return file_hannah_infrastructure_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceEndpoint) GetKind() ServiceKind {
	if x != nil {
		return x.Kind
	}
	return ServiceKind_SERVICE_KIND_UNSPECIFIED
}

func (x *ServiceEndpoint) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *ServiceEndpoint) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ServiceEndpoint) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServiceEndpoint) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Which kinds of service the subscriber cares about. Empty = all kinds.
type InfrastructureFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kinds []ServiceKind `protobuf:"varint,1,rep,packed,name=kinds,proto3,enum=hannah.ServiceKind" json:"kinds,omitempty"`
}

func (x *InfrastructureFilter) Reset() {
	*x = InfrastructureFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_infrastructure_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfrastructureFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfrastructureFilter) ProtoMessage() {}

func (x *InfrastructureFilter) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_infrastructure_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfrastructureFilter.ProtoReflect.Descriptor instead.
func (*InfrastructureFilter) Descriptor() ([]byte, []int) {
	return file_hannah_infrastructure_proto_rawDescGZIP(), []int{1}
}

func (x *InfrastructureFilter) GetKinds() []ServiceKind {
	if x != nil {
		return x.Kinds
	}
	return nil
}

type InfrastructureMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//	*InfrastructureMessage_Snapshot
	//	*InfrastructureMessage_Available
	//	*InfrastructureMessage_Unavailable
	Payload isInfrastructureMessage_Payload `protobuf_oneof:"payload"`
}

func (x *InfrastructureMessage) Reset() {
	*x = InfrastructureMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_infrastructure_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfrastructureMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfrastructureMessage) ProtoMessage() {}

func (x *InfrastructureMessage) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_infrastructure_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfrastructureMessage.ProtoReflect.Descriptor instead.
func (*InfrastructureMessage) Descriptor() ([]byte, []int) {
	return file_hannah_infrastructure_proto_rawDescGZIP(), []int{2}
}

func (m *InfrastructureMessage) GetPayload() isInfrastructureMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *InfrastructureMessage) GetSnapshot() *InfrastructureSnapshot {
	if x, ok := x.GetPayload().(*InfrastructureMessage_Snapshot); ok {
		return x.Snapshot
	}
	return nil
}

func (x *InfrastructureMessage) GetAvailable() *ServiceAvailable {
	if x, ok := x.GetPayload().(*InfrastructureMessage_Available); ok {
		return x.Available
	}
	return nil
}

func (x *InfrastructureMessage) GetUnavailable() *ServiceUnavailable {
	if x, ok := x.GetPayload().(*InfrastructureMessage_Unavailable); ok {
		return x.Unavailable
	}
	return nil
}

type isInfrastructureMessage_Payload interface {
	isInfrastructureMessage_Payload()
}

type InfrastructureMessage_Snapshot struct {
	Snapshot *InfrastructureSnapshot `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof"` // sent once, right after subscribing
}

type InfrastructureMessage_Available struct {
	Available *ServiceAvailable `protobuf:"bytes,2,opt,name=available,proto3,oneof"` // live delta
}

type InfrastructureMessage_Unavailable struct {
	Unavailable *ServiceUnavailable `protobuf:"bytes,3,opt,name=unavailable,proto3,oneof"` // live delta
}

func (*InfrastructureMessage_Snapshot) isInfrastructureMessage_Payload() {}

func (*InfrastructureMessage_Available) isInfrastructureMessage_Payload() {}

func (*InfrastructureMessage_Unavailable) isInfrastructureMessage_Payload() {}

// All matching services available right now. Sent once per subscription, before any
// delta — a subscriber replaces its whole state with it, so a reconnect never keeps a
// service that disappeared while it was offline.
type InfrastructureSnapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Services []*ServiceEndpoint `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
}

func (x *InfrastructureSnapshot) Reset() {
	*x = InfrastructureSnapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_infrastructure_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfrastructureSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfrastructureSnapshot) ProtoMessage() {}

func (x *InfrastructureSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_infrastructure_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfrastructureSnapshot.ProtoReflect.Descriptor instead.
func (*InfrastructureSnapshot) Descriptor() ([]byte, []int) {
	return file_hannah_infrastructure_proto_rawDescGZIP(), []int{3}
}

func (x *InfrastructureSnapshot) GetServices() []*ServiceEndpoint {
	if x != nil {
		return x.Services
	}
	return nil
}

// A service became available, or an available one re-registered (e.g. new address).
type ServiceAvailable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service *ServiceEndpoint `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
}

func (x *ServiceAvailable) Reset() {
	*x = ServiceAvailable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_infrastructure_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceAvailable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAvailable) ProtoMessage() {}

func (x *ServiceAvailable) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_infrastructure_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAvailable.ProtoReflect.Descriptor instead.
func (*ServiceAvailable) Descriptor() ([]byte, []int) {
	return file_hannah_infrastructure_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceAvailable) GetService() *ServiceEndpoint {
	if x != nil {
		return x.Service
	}
	return nil
}

// A service is no longer available (its registration stream ended or was displaced).
type ServiceUnavailable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind     ServiceKind `protobuf:"varint,1,opt,name=kind,proto3,enum=hannah.ServiceKind" json:"kind,omitempty"`
	Instance string      `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
}

func (x *ServiceUnavailable) Reset() {
	*x = ServiceUnavailable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_infrastructure_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceUnavailable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceUnavailable) ProtoMessage() {}

func (x *ServiceUnavailable) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_infrastructure_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceUnavailable.ProtoReflect.Descriptor instead.
func (*ServiceUnavailable) Descriptor() ([]byte, []int) {
	return file_hannah_infrastructure_proto_rawDescGZIP(), []int{5}
}

func (x *ServiceUnavailable) GetKind() ServiceKind {
	if x != nil {
		return x.Kind
	}
	return ServiceKind_SERVICE_KIND_UNSPECIFIED
}

func (x *ServiceUnavailable) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

// Sent by the log collector over the LogCollectorConnect stream.
type LogCollectorMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//	*LogCollectorMessage_Register
	Payload isLogCollectorMessage_Payload `protobuf_oneof:"payload"`
}

func (x *LogCollectorMessage) Reset() {
	*x = LogCollectorMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_infrastructure_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogCollectorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogCollectorMessage) ProtoMessage() {}

func (x *LogCollectorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_infrastructure_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogCollectorMessage.ProtoReflect.Descriptor instead.
func (*LogCollectorMessage) Descriptor() ([]byte, []int) {
	return file_hannah_infrastructure_proto_rawDescGZIP(), []int{6}
}

func (m *LogCollectorMessage) GetPayload() isLogCollectorMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *LogCollectorMessage) GetRegister() *LogCollectorRegister {
	if x, ok := x.GetPayload().(*LogCollectorMessage_Register); ok {
		return x.Register
	}
	return nil
}

type isLogCollectorMessage_Payload interface {
	isLogCollectorMessage_Payload()
}

type LogCollectorMessage_Register struct {
	Register *LogCollectorRegister `protobuf:"bytes,1,opt,name=register,proto3,oneof"` // sent once, right after connecting
}

func (*LogCollectorMessage_Register) isLogCollectorMessage_Payload() {}

// A second log collector registering with the same instance replaces the first.
type LogCollectorRegister struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Instance string `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Host     string `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"` // empty = Hannah Core uses the stream's peer address
	Port     int32  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Version  string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"` // informational
}

func (x *LogCollectorRegister) Reset() {
	*x = LogCollectorRegister{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_infrastructure_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogCollectorRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogCollectorRegister) ProtoMessage() {}

func (x *LogCollectorRegister) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_infrastructure_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogCollectorRegister.ProtoReflect.Descriptor instead.
func (*LogCollectorRegister) Descriptor() ([]byte, []int) {
	return file_hannah_infrastructure_proto_rawDescGZIP(), []int{7}
}

func (x *LogCollectorRegister) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *LogCollectorRegister) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *LogCollectorRegister) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *LogCollectorRegister) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Sent by Hannah Core over the LogCollectorConnect stream.
type LogCollectorCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Command:
	//	*LogCollectorCommand_Registered
	Command isLogCollectorCommand_Command `protobuf_oneof:"command"`
}

func (x *LogCollectorCommand) Reset() {
	*x = LogCollectorCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_infrastructure_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogCollectorCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogCollectorCommand) ProtoMessage() {}

func (x *LogCollectorCommand) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_infrastructure_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogCollectorCommand.ProtoReflect.Descriptor instead.
func (*LogCollectorCommand) Descriptor() ([]byte, []int) {
	return file_hannah_infrastructure_proto_rawDescGZIP(), []int{8}
}

func (m *LogCollectorCommand) GetCommand() isLogCollectorCommand_Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (x *LogCollectorCommand) GetRegistered() *LogCollectorRegistered {
	if x, ok := x.GetCommand().(*LogCollectorCommand_Registered); ok {
		return x.Registered
	}
	return nil
}

type isLogCollectorCommand_Command interface {
	isLogCollectorCommand_Command()
}

type LogCollectorCommand_Registered struct {
	Registered *LogCollectorRegistered `protobuf:"bytes,1,opt,name=registered,proto3,oneof"` // sent once, right after register
}

func (*LogCollectorCommand_Registered) isLogCollectorCommand_Command() {}

type LogCollectorRegistered struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LogCollectorRegistered) Reset() {
	*x = LogCollectorRegistered{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_infrastructure_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogCollectorRegistered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogCollectorRegistered) ProtoMessage() {}

func (x *LogCollectorRegistered) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_infrastructure_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogCollectorRegistered.ProtoReflect.Descriptor instead.
func (*LogCollectorRegistered) Descriptor() ([]byte, []int) {
	return file_hannah_infrastructure_proto_rawDescGZIP(), []int{9}
}

var File_hannah_infrastructure_proto protoreflect.FileDescriptor

var file_hannah_infrastructure_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x73, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x68,
	0x61, 0x6e, 0x6e, 0x61, 0x68, 0x22, 0x98, 0x01, 0x0a, 0x0f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x04, 0x6b, 0x69, 0x6e,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69,
	0x6e, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x22, 0x41, 0x0a, 0x14, 0x49, 0x6e, 0x66, 0x72, 0x61, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x29, 0x0a, 0x05, 0x6b, 0x69, 0x6e, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x05, 0x6b, 0x69,
	0x6e, 0x64, 0x73, 0x22, 0xda, 0x01, 0x0a, 0x15, 0x49, 0x6e, 0x66, 0x72, 0x61, 0x73, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3c, 0x0a,
	0x08, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x49, 0x6e, 0x66, 0x72, 0x61, 0x73, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x48,
	0x00, 0x52, 0x08, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x61,
	0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41,
	0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x09, 0x61, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x3e, 0x0a, 0x0b, 0x75, 0x6e, 0x61, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x68, 0x61, 0x6e,
	0x6e, 0x61, 0x68, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55, 0x6e, 0x61, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x0b, 0x75, 0x6e, 0x61, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x22, 0x4d, 0x0a, 0x16, 0x49, 0x6e, 0x66, 0x72, 0x61, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x33, 0x0a, 0x08, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x68,
	0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x6e, 0x64,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22,
	0x45, 0x0a, 0x10, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61,
	0x62, 0x6c, 0x65, 0x12, 0x31, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x07, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x59, 0x0a, 0x12, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x55, 0x6e, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x27, 0x0a, 0x04,
	0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x68, 0x61, 0x6e,
	0x6e, 0x61, 0x68, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x52,
	0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x22, 0x5c, 0x0a, 0x13, 0x4c, 0x6f, 0x67, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3a, 0x0a, 0x08, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x68, 0x61, 0x6e,
	0x6e, 0x61, 0x68, 0x2e, 0x4c, 0x6f, 0x67, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22,
	0x74, 0x0a, 0x14, 0x4c, 0x6f, 0x67, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x62, 0x0a, 0x13, 0x4c, 0x6f, 0x67, 0x43, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x40, 0x0a, 0x0a,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x4c, 0x6f, 0x67, 0x43, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64,
	0x48, 0x00, 0x52, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x42, 0x09,
	0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x18, 0x0a, 0x16, 0x4c, 0x6f, 0x67,
	0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x65, 0x64, 0x2a, 0x4b, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4b, 0x69,
	0x6e, 0x64, 0x12, 0x1c, 0x0a, 0x18, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x4b, 0x49,
	0x4e, 0x44, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x1e, 0x0a, 0x1a, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x4b, 0x49, 0x4e, 0x44,
	0x5f, 0x4c, 0x4f, 0x47, 0x5f, 0x43, 0x4f, 0x4c, 0x4c, 0x45, 0x43, 0x54, 0x4f, 0x52, 0x10, 0x01,
	0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4e,
	0x75, 0x72, 0x50, 0x65, 0x63, 0x68, 0x2f, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2d, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x6f, 0x3b, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hannah_infrastructure_proto_rawDescOnce sync.Once
	file_hannah_infrastructure_proto_rawDescData = file_hannah_infrastructure_proto_rawDesc
)

func file_hannah_infrastructure_proto_rawDescGZIP() []byte {
	file_hannah_infrastructure_proto_rawDescOnce.Do(func() {
		file_hannah_infrastructure_proto_rawDescData = protoimpl.X.CompressGZIP(file_hannah_infrastructure_proto_rawDescData)
	})
	return file_hannah_infrastructure_proto_rawDescData
}

var file_hannah_infrastructure_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hannah_infrastructure_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_hannah_infrastructure_proto_goTypes = []any{
	(ServiceKind)(0),               // 0: hannah.ServiceKind
	(*ServiceEndpoint)(nil),        // 1: hannah.ServiceEndpoint
	(*InfrastructureFilter)(nil),   // 2: hannah.InfrastructureFilter
	(*InfrastructureMessage)(nil),  // 3: hannah.InfrastructureMessage
	(*InfrastructureSnapshot)(nil), // 4: hannah.InfrastructureSnapshot
	(*ServiceAvailable)(nil),       // 5: hannah.ServiceAvailable
	(*ServiceUnavailable)(nil),     // 6: hannah.ServiceUnavailable
	(*LogCollectorMessage)(nil),    // 7: hannah.LogCollectorMessage
	(*LogCollectorRegister)(nil),   // 8: hannah.LogCollectorRegister
	(*LogCollectorCommand)(nil),    // 9: hannah.LogCollectorCommand
	(*LogCollectorRegistered)(nil), // 10: hannah.LogCollectorRegistered
}
var file_hannah_infrastructure_proto_depIdxs = []int32{
	0,  // 0: hannah.ServiceEndpoint.kind:type_name -> hannah.ServiceKind
	0,  // 1: hannah.InfrastructureFilter.kinds:type_name -> hannah.ServiceKind
	4,  // 2: hannah.InfrastructureMessage.snapshot:type_name -> hannah.InfrastructureSnapshot
	5,  // 3: hannah.InfrastructureMessage.available:type_name -> hannah.ServiceAvailable
	6,  // 4: hannah.InfrastructureMessage.unavailable:type_name -> hannah.ServiceUnavailable
	1,  // 5: hannah.InfrastructureSnapshot.services:type_name -> hannah.ServiceEndpoint
	1,  // 6: hannah.ServiceAvailable.service:type_name -> hannah.ServiceEndpoint
	0,  // 7: hannah.ServiceUnavailable.kind:type_name -> hannah.ServiceKind
	8,  // 8: hannah.LogCollectorMessage.register:type_name -> hannah.LogCollectorRegister
	10, // 9: hannah.LogCollectorCommand.registered:type_name -> hannah.LogCollectorRegistered
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_hannah_infrastructure_proto_init() }
func file_hannah_infrastructure_proto_init() {
	if File_hannah_infrastructure_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hannah_infrastructure_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ServiceEndpoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_infrastructure_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*InfrastructureFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_infrastructure_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*InfrastructureMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_infrastructure_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*InfrastructureSnapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_infrastructure_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ServiceAvailable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_infrastructure_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ServiceUnavailable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_infrastructure_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*LogCollectorMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_infrastructure_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*LogCollectorRegister); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_infrastructure_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*LogCollectorCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_infrastructure_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*LogCollectorRegistered); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_hannah_infrastructure_proto_msgTypes[2].OneofWrappers = []any{
		(*InfrastructureMessage_Snapshot)(nil),
		(*InfrastructureMessage_Available)(nil),
		(*InfrastructureMessage_Unavailable)(nil),
	}
	file_hannah_infrastructure_proto_msgTypes[6].OneofWrappers = []any{
		(*LogCollectorMessage_Register)(nil),
	}
	file_hannah_infrastructure_proto_msgTypes[8].OneofWrappers = []any{
		(*LogCollectorCommand_Registered)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hannah_infrastructure_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hannah_infrastructure_proto_goTypes,
		DependencyIndexes: file_hannah_infrastructure_proto_depIdxs,
		EnumInfos:         file_hannah_infrastructure_proto_enumTypes,
		MessageInfos:      file_hannah_infrastructure_proto_msgTypes,
	}.Build()
	File_hannah_infrastructure_proto = out.File
	file_hannah_infrastructure_proto_rawDesc = nil
	file_hannah_infrastructure_proto_goTypes = nil
	file_hannah_infrastructure_proto_depIdxs = nil
}
