// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: hannah/logging.proto

package hannahproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogLevel int32

const (
	LogLevel_LOG_LEVEL_UNSPECIFIED LogLevel = 0
	LogLevel_LOG_LEVEL_DEBUG       LogLevel = 1
	LogLevel_LOG_LEVEL_INFO        LogLevel = 2
	LogLevel_LOG_LEVEL_WARNING     LogLevel = 3
	LogLevel_LOG_LEVEL_ERROR       LogLevel = 4
	LogLevel_LOG_LEVEL_CRITICAL    LogLevel = 5
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LOG_LEVEL_UNSPECIFIED",
		1: "LOG_LEVEL_DEBUG",
		2: "LOG_LEVEL_INFO",
		3: "LOG_LEVEL_WARNING",
		4: "LOG_LEVEL_ERROR",
		5: "LOG_LEVEL_CRITICAL",
	}
	LogLevel_value = map[string]int32{
		"LOG_LEVEL_UNSPECIFIED": 0,
		"LOG_LEVEL_DEBUG":       1,
		"LOG_LEVEL_INFO":        2,
		"LOG_LEVEL_WARNING":     3,
		"LOG_LEVEL_ERROR":       4,
		"LOG_LEVEL_CRITICAL":    5,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_hannah_logging_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_hannah_logging_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_hannah_logging_proto_rawDescGZIP(), []int{0}
}

// Lets an export leave out sensitive content (e.g. before posting it in a forum).
type LogCategory int32

const (
	LogCategory_LOG_CATEGORY_UNSPECIFIED LogCategory = 0
	LogCategory_LOG_CATEGORY_GENERAL     LogCategory = 1
	LogCategory_LOG_CATEGORY_TRANSCRIPT  LogCategory = 2 // speech transcripts / user utterances
	LogCategory_LOG_CATEGORY_METADATA    LogCategory = 3 // room/device names, presence and similar
)

// Enum value maps for LogCategory.
var (
	LogCategory_name = map[int32]string{
		0: "LOG_CATEGORY_UNSPECIFIED",
		1: "LOG_CATEGORY_GENERAL",
		2: "LOG_CATEGORY_TRANSCRIPT",
		3: "LOG_CATEGORY_METADATA",
	}
	LogCategory_value = map[string]int32{
		"LOG_CATEGORY_UNSPECIFIED": 0,
		"LOG_CATEGORY_GENERAL":     1,
		"LOG_CATEGORY_TRANSCRIPT":  2,
		"LOG_CATEGORY_METADATA":    3,
	}
)

func (x LogCategory) Enum() *LogCategory {
	p := new(LogCategory)
	*p = x
	return p
}

func (x LogCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_hannah_logging_proto_enumTypes[1].Descriptor()
}

func (LogCategory) Type() protoreflect.EnumType {
	return &file_hannah_logging_proto_enumTypes[1]
}

func (x LogCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogCategory.Descriptor instead.
func (LogCategory) EnumDescriptor() ([]byte, []int) {
	return file_hannah_logging_proto_rawDescGZIP(), []int{1}
}

type ShipMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//	*ShipMessage_Hello
	//	*ShipMessage_Entry
	//	*ShipMessage_Gap
	Payload isShipMessage_Payload `protobuf_oneof:"payload"`
}

func (x *ShipMessage) Reset() {
	*x = ShipMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_logging_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShipMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipMessage) ProtoMessage() {}

func (x *ShipMessage) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_logging_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipMessage.ProtoReflect.Descriptor instead.
func (*ShipMessage) Descriptor() ([]byte, []int) {
	return file_hannah_logging_proto_rawDescGZIP(), []int{0}
}

func (m *ShipMessage) GetPayload() isShipMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *ShipMessage) GetHello() *ShipHello {
	if x, ok := x.GetPayload().(*ShipMessage_Hello); ok {
		return x.Hello
	}
	return nil
}

func (x *ShipMessage) GetEntry() *LogEntry {
	if x, ok := x.GetPayload().(*ShipMessage_Entry); ok {
		return x.Entry
	}
	return nil
}

func (x *ShipMessage) GetGap() *LogGap {
	if x, ok := x.GetPayload().(*ShipMessage_Gap); ok {
		return x.Gap
	}
	return nil
}

type isShipMessage_Payload interface {
	isShipMessage_Payload()
}

type ShipMessage_Hello struct {
	Hello *ShipHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"` // exactly once, as the first message
}

type ShipMessage_Entry struct {
	Entry *LogEntry `protobuf:"bytes,2,opt,name=entry,proto3,oneof"`
}

type ShipMessage_Gap struct {
	Gap *LogGap `protobuf:"bytes,3,opt,name=gap,proto3,oneof"` // the component's buffer overflowed, entries were dropped
}

func (*ShipMessage_Hello) isShipMessage_Payload() {}

func (*ShipMessage_Entry) isShipMessage_Payload() {}

func (*ShipMessage_Gap) isShipMessage_Payload() {}

// Identifies the source of all entries on this stream.
type ShipHello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Component string `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"` // e.g. "core", "telegram", "voiceid"
	Instance  string `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`   // distinguishes several instances of the same component
	Version   string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`     // component version, shown in the export manifest
}

func (x *ShipHello) Reset() {
	*x = ShipHello{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_logging_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShipHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipHello) ProtoMessage() {}

func (x *ShipHello) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_logging_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipHello.ProtoReflect.Descriptor instead.
func (*ShipHello) Descriptor() ([]byte, []int) {
	return file_hannah_logging_proto_rawDescGZIP(), []int{1}
}

func (x *ShipHello) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *ShipHello) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *ShipHello) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type LogEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimestampMs int64       `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"` // Unix ms at the time of logging in the component, not of receipt
	Level       LogLevel    `protobuf:"varint,2,opt,name=level,proto3,enum=hannah.LogLevel" json:"level,omitempty"`
	Logger      string      `protobuf:"bytes,3,opt,name=logger,proto3" json:"logger,omitempty"`   // e.g. the Python logger name
	Message     string      `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"` // secrets are filtered out by the component before sending
	Category    LogCategory `protobuf:"varint,5,opt,name=category,proto3,enum=hannah.LogCategory" json:"category,omitempty"`
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_logging_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_logging_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_hannah_logging_proto_rawDescGZIP(), []int{2}
}

func (x *LogEntry) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *LogEntry) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *LogEntry) GetLogger() string {
	if x != nil {
		return x.Logger
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetCategory() LogCategory {
	if x != nil {
		return x.Category
	}
	return LogCategory_LOG_CATEGORY_UNSPECIFIED
}

// Entries the component had to drop (buffer overflow while the collector was
// unreachable). Listed in the export manifest so gaps are visible.
type LogGap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dropped int64 `protobuf:"varint,1,opt,name=dropped,proto3" json:"dropped,omitempty"`
	FromMs  int64 `protobuf:"varint,2,opt,name=from_ms,json=fromMs,proto3" json:"from_ms,omitempty"`
	ToMs    int64 `protobuf:"varint,3,opt,name=to_ms,json=toMs,proto3" json:"to_ms,omitempty"`
}

func (x *LogGap) Reset() {
	*x = LogGap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_logging_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogGap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogGap) ProtoMessage() {}

func (x *LogGap) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_logging_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogGap.ProtoReflect.Descriptor instead.
func (*LogGap) Descriptor() ([]byte, []int) {
	return file_hannah_logging_proto_rawDescGZIP(), []int{3}
}

func (x *LogGap) GetDropped() int64 {
	if x != nil {
		return x.Dropped
	}
	return 0
}

func (x *LogGap) GetFromMs() int64 {
	if x != nil {
		return x.FromMs
	}
	return 0
}

func (x *LogGap) GetToMs() int64 {
	if x != nil {
		return x.ToMs
	}
	return 0
}

type ShipAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Accepted int64 `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"` // number of entries stored from this stream
}

func (x *ShipAck) Reset() {
	*x = ShipAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_logging_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShipAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipAck) ProtoMessage() {}

func (x *ShipAck) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_logging_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipAck.ProtoReflect.Descriptor instead.
func (*ShipAck) Descriptor() ([]byte, []int) {
	return file_hannah_logging_proto_rawDescGZIP(), []int{4}
}

func (x *ShipAck) GetAccepted() int64 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

type LogSource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Component string `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"`
	Instance  string `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	Version   string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"` // from the most recent ShipHello
	OldestMs  int64  `protobuf:"varint,4,opt,name=oldest_ms,json=oldestMs,proto3" json:"oldest_ms,omitempty"`
	NewestMs  int64  `protobuf:"varint,5,opt,name=newest_ms,json=newestMs,proto3" json:"newest_ms,omitempty"`
	Entries   int64  `protobuf:"varint,6,opt,name=entries,proto3" json:"entries,omitempty"`
}

func (x *LogSource) Reset() {
	*x = LogSource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_logging_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogSource) ProtoMessage() {}

func (x *LogSource) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_logging_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogSource.ProtoReflect.Descriptor instead.
func (*LogSource) Descriptor() ([]byte, []int) {
	return file_hannah_logging_proto_rawDescGZIP(), []int{5}
}

func (x *LogSource) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *LogSource) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *LogSource) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *LogSource) GetOldestMs() int64 {
	if x != nil {
		return x.OldestMs
	}
	return 0
}

func (x *LogSource) GetNewestMs() int64 {
	if x != nil {
		return x.NewestMs
	}
	return 0
}

func (x *LogSource) GetEntries() int64 {
	if x != nil {
		return x.Entries
	}
	return 0
}

type GetSourcesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sources []*LogSource `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
}

func (x *GetSourcesResponse) Reset() {
	*x = GetSourcesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_logging_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSourcesResponse) ProtoMessage() {}

func (x *GetSourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_logging_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSourcesResponse.ProtoReflect.Descriptor instead.
func (*GetSourcesResponse) Descriptor() ([]byte, []int) {
	return file_hannah_logging_proto_rawDescGZIP(), []int{6}
}

func (x *GetSourcesResponse) GetSources() []*LogSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

type ExportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SinceMs           int64         `protobuf:"varint,1,opt,name=since_ms,json=sinceMs,proto3" json:"since_ms,omitempty"`
	UntilMs           int64         `protobuf:"varint,2,opt,name=until_ms,json=untilMs,proto3" json:"until_ms,omitempty"` // 0 = now
	Components        []string      `protobuf:"bytes,3,rep,name=components,proto3" json:"components,omitempty"`           // empty = all
	ExcludeCategories []LogCategory `protobuf:"varint,4,rep,packed,name=exclude_categories,json=excludeCategories,proto3,enum=hannah.LogCategory" json:"exclude_categories,omitempty"`
}

func (x *ExportRequest) Reset() {
	*x = ExportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_logging_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRequest) ProtoMessage() {}

func (x *ExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_logging_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRequest.ProtoReflect.Descriptor instead.
func (*ExportRequest) Descriptor() ([]byte, []int) {
	return file_hannah_logging_proto_rawDescGZIP(), []int{7}
}

func (x *ExportRequest) GetSinceMs() int64 {
	if x != nil {
		return x.SinceMs
	}
	return 0
}

func (x *ExportRequest) GetUntilMs() int64 {
	if x != nil {
		return x.UntilMs
	}
	return 0
}

func (x *ExportRequest) GetComponents() []string {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *ExportRequest) GetExcludeCategories() []LogCategory {
	if x != nil {
		return x.ExcludeCategories
	}
	return nil
}

type ExportChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ExportChunk) Reset() {
	*x = ExportChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_logging_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportChunk) ProtoMessage() {}

func (x *ExportChunk) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_logging_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportChunk.ProtoReflect.Descriptor instead.
func (*ExportChunk) Descriptor() ([]byte, []int) {
	return file_hannah_logging_proto_rawDescGZIP(), []int{8}
}

func (x *ExportChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_hannah_logging_proto protoreflect.FileDescriptor

var file_hannah_logging_proto_rawDesc = []byte{
	0x0a, 0x14, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2f, 0x6c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x1a, 0x13,
	0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x91, 0x01, 0x0a, 0x0b, 0x53, 0x68, 0x69, 0x70, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x53, 0x68, 0x69, 0x70,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x48, 0x00, 0x52, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x28,
	0x0a, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x48,
	0x00, 0x52, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x22, 0x0a, 0x03, 0x67, 0x61, 0x70, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x4c,
	0x6f, 0x67, 0x47, 0x61, 0x70, 0x48, 0x00, 0x52, 0x03, 0x67, 0x61, 0x70, 0x42, 0x09, 0x0a, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x5f, 0x0a, 0x09, 0x53, 0x68, 0x69, 0x70, 0x48,
	0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65,
	0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xb8, 0x01, 0x0a, 0x08, 0x4c, 0x6f, 0x67,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x5f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x4d, 0x73, 0x12, 0x26, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68,
	0x2e, 0x4c, 0x6f, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x12, 0x16, 0x0a, 0x06, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x2f, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x4c, 0x6f,
	0x67, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x22, 0x50, 0x0a, 0x06, 0x4c, 0x6f, 0x67, 0x47, 0x61, 0x70, 0x12, 0x18, 0x0a,
	0x07, 0x64, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x64, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x72, 0x6f, 0x6d, 0x5f,
	0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x4d, 0x73,
	0x12, 0x13, 0x0a, 0x05, 0x74, 0x6f, 0x5f, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x74, 0x6f, 0x4d, 0x73, 0x22, 0x25, 0x0a, 0x07, 0x53, 0x68, 0x69, 0x70, 0x41, 0x63, 0x6b,
	0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x22, 0xb3, 0x01, 0x0a,
	0x09, 0x4c, 0x6f, 0x67, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f,
	0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63,
	0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1b,
	0x0a, 0x09, 0x6f, 0x6c, 0x64, 0x65, 0x73, 0x74, 0x5f, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x6f, 0x6c, 0x64, 0x65, 0x73, 0x74, 0x4d, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x6e,
	0x65, 0x77, 0x65, 0x73, 0x74, 0x5f, 0x6d, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x6e, 0x65, 0x77, 0x65, 0x73, 0x74, 0x4d, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72,
	0x69, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69,
	0x65, 0x73, 0x22, 0x41, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x07, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x68, 0x61, 0x6e, 0x6e,
	0x61, 0x68, 0x2e, 0x4c, 0x6f, 0x67, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x07, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x22, 0xa9, 0x01, 0x0a, 0x0d, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x69, 0x6e, 0x63, 0x65,
	0x5f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x69, 0x6e, 0x63, 0x65,
	0x4d, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x6e, 0x74, 0x69, 0x6c, 0x5f, 0x6d, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x75, 0x6e, 0x74, 0x69, 0x6c, 0x4d, 0x73, 0x12, 0x1e, 0x0a,
	0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x42, 0x0a,
	0x12, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x69, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x68, 0x61, 0x6e, 0x6e,
	0x61, 0x68, 0x2e, 0x4c, 0x6f, 0x67, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x11,
	0x65, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65,
	0x73, 0x22, 0x21, 0x0a, 0x0b, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x68, 0x75, 0x6e, 0x6b,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x2a, 0x92, 0x01, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x12, 0x19, 0x0a, 0x15, 0x4c, 0x4f, 0x47, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f,
	0x4c, 0x4f, 0x47, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x44, 0x45, 0x42, 0x55, 0x47, 0x10,
	0x01, 0x12, 0x12, 0x0a, 0x0e, 0x4c, 0x4f, 0x47, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x49,
	0x4e, 0x46, 0x4f, 0x10, 0x02, 0x12, 0x15, 0x0a, 0x11, 0x4c, 0x4f, 0x47, 0x5f, 0x4c, 0x45, 0x56,
	0x45, 0x4c, 0x5f, 0x57, 0x41, 0x52, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x12, 0x13, 0x0a, 0x0f,
	0x4c, 0x4f, 0x47, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10,
	0x04, 0x12, 0x16, 0x0a, 0x12, 0x4c, 0x4f, 0x47, 0x5f, 0x4c, 0x45, 0x56, 0x45, 0x4c, 0x5f, 0x43,
	0x52, 0x49, 0x54, 0x49, 0x43, 0x41, 0x4c, 0x10, 0x05, 0x2a, 0x7d, 0x0a, 0x0b, 0x4c, 0x6f, 0x67,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x1c, 0x0a, 0x18, 0x4c, 0x4f, 0x47, 0x5f,
	0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x4c, 0x4f, 0x47, 0x5f, 0x43, 0x41,
	0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x47, 0x45, 0x4e, 0x45, 0x52, 0x41, 0x4c, 0x10, 0x01,
	0x12, 0x1b, 0x0a, 0x17, 0x4c, 0x4f, 0x47, 0x5f, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59,
	0x5f, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x43, 0x52, 0x49, 0x50, 0x54, 0x10, 0x02, 0x12, 0x19, 0x0a,
	0x15, 0x4c, 0x4f, 0x47, 0x5f, 0x43, 0x41, 0x54, 0x45, 0x47, 0x4f, 0x52, 0x59, 0x5f, 0x4d, 0x45,
	0x54, 0x41, 0x44, 0x41, 0x54, 0x41, 0x10, 0x03, 0x32, 0xad, 0x01, 0x0a, 0x0a, 0x4c, 0x6f, 0x67,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x53, 0x68, 0x69, 0x70, 0x12,
	0x13, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x53, 0x68, 0x69, 0x70, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x1a, 0x0f, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x53, 0x68,
	0x69, 0x70, 0x41, 0x63, 0x6b, 0x28, 0x01, 0x12, 0x37, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x53, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x0d, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1a, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x47, 0x65,
	0x74, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x36, 0x0a, 0x06, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x15, 0x2e, 0x68, 0x61, 0x6e,
	0x6e, 0x61, 0x68, 0x2e, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x13, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x45, 0x78, 0x70, 0x6f, 0x72,
	0x74, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x30, 0x01, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4e, 0x75, 0x72, 0x50, 0x65, 0x63, 0x68, 0x2f, 0x68,
	0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x6f, 0x3b, 0x68,
	0x61, 0x6e, 0x6e, 0x61, 0x68, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_hannah_logging_proto_rawDescOnce sync.Once
	file_hannah_logging_proto_rawDescData = file_hannah_logging_proto_rawDesc
)

func file_hannah_logging_proto_rawDescGZIP() []byte {
	file_hannah_logging_proto_rawDescOnce.Do(func() {
		file_hannah_logging_proto_rawDescData = protoimpl.X.CompressGZIP(file_hannah_logging_proto_rawDescData)
	})
	return file_hannah_logging_proto_rawDescData
}

var file_hannah_logging_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_hannah_logging_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_hannah_logging_proto_goTypes = []any{
	(LogLevel)(0),              // 0: hannah.LogLevel
	(LogCategory)(0),           // 1: hannah.LogCategory
	(*ShipMessage)(nil),        // 2: hannah.ShipMessage
	(*ShipHello)(nil),          // 3: hannah.ShipHello
	(*LogEntry)(nil),           // 4: hannah.LogEntry
	(*LogGap)(nil),             // 5: hannah.LogGap
	(*ShipAck)(nil),            // 6: hannah.ShipAck
	(*LogSource)(nil),          // 7: hannah.LogSource
	(*GetSourcesResponse)(nil), // 8: hannah.GetSourcesResponse
	(*ExportRequest)(nil),      // 9: hannah.ExportRequest
	(*ExportChunk)(nil),        // 10: hannah.ExportChunk
	(*Empty)(nil),              // 11: hannah.Empty
}
var file_hannah_logging_proto_depIdxs = []int32{
	3,  // 0: hannah.ShipMessage.hello:type_name -> hannah.ShipHello
	4,  // 1: hannah.ShipMessage.entry:type_name -> hannah.LogEntry
	5,  // 2: hannah.ShipMessage.gap:type_name -> hannah.LogGap
	0,  // 3: hannah.LogEntry.level:type_name -> hannah.LogLevel
	1,  // 4: hannah.LogEntry.category:type_name -> hannah.LogCategory
	7,  // 5: hannah.GetSourcesResponse.sources:type_name -> hannah.LogSource
	1,  // 6: hannah.ExportRequest.exclude_categories:type_name -> hannah.LogCategory
	2,  // 7: hannah.LogService.Ship:input_type -> hannah.ShipMessage
	11, // 8: hannah.LogService.GetSources:input_type -> hannah.Empty
	9,  // 9: hannah.LogService.Export:input_type -> hannah.ExportRequest
	6,  // 10: hannah.LogService.Ship:output_type -> hannah.ShipAck
	8,  // 11: hannah.LogService.GetSources:output_type -> hannah.GetSourcesResponse
	10, // 12: hannah.LogService.Export:output_type -> hannah.ExportChunk
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_hannah_logging_proto_init() }
func file_hannah_logging_proto_init() {
	if File_hannah_logging_proto != nil {
		return
	}
	file_hannah_shared_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_hannah_logging_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ShipMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_logging_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ShipHello); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_logging_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*LogEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_logging_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*LogGap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_logging_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ShipAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_logging_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*LogSource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_logging_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetSourcesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_logging_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*ExportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_logging_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*ExportChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_hannah_logging_proto_msgTypes[0].OneofWrappers = []any{
		(*ShipMessage_Hello)(nil),
		(*ShipMessage_Entry)(nil),
		(*ShipMessage_Gap)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hannah_logging_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hannah_logging_proto_goTypes,
		DependencyIndexes: file_hannah_logging_proto_depIdxs,
		EnumInfos:         file_hannah_logging_proto_enumTypes,
		MessageInfos:      file_hannah_logging_proto_msgTypes,
	}.Build()
	File_hannah_logging_proto = out.File
	file_hannah_logging_proto_rawDesc = nil
	file_hannah_logging_proto_goTypes = nil
	file_hannah_logging_proto_depIdxs = nil
}
