// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: hannah/logging.proto

package hannahproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogService_Ship_FullMethodName       = "/hannah.LogService/Ship"
	LogService_GetSources_FullMethodName = "/hannah.LogService/GetSources"
	LogService_Export_FullMethodName     = "/hannah.LogService/Export"
)

// LogServiceClient is the client API for LogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogServiceClient interface {
	// Component → collector. First message is a ShipHello, then any number of
	// entries/gaps. The stream stays open for as long as the component runs.
	Ship(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ShipMessage, ShipAck], error)
	// Which sources the collector currently holds logs for, and how far back.
	GetSources(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetSourcesResponse, error)
	// Archive of the requested logs (tar.gz: one file per source plus a manifest),
	// split into chunks — the client concatenates ExportChunk.data in order.
	Export(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExportChunk], error)
}

type logServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogServiceClient(cc grpc.ClientConnInterface) LogServiceClient {
	return &logServiceClient{cc}
}

func (c *logServiceClient) Ship(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ShipMessage, ShipAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LogService_ServiceDesc.Streams[0], LogService_Ship_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ShipMessage, ShipAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LogService_ShipClient = grpc.ClientStreamingClient[ShipMessage, ShipAck]

func (c *logServiceClient) GetSources(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetSourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSourcesResponse)
	err := c.cc.Invoke(ctx, LogService_GetSources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) Export(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExportChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LogService_ServiceDesc.Streams[1], LogService_Export_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExportRequest, ExportChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LogService_ExportClient = grpc.ServerStreamingClient[ExportChunk]

// LogServiceServer is the server API for LogService service.
// All implementations must embed UnimplementedLogServiceServer
// for forward compatibility.
type LogServiceServer interface {
	// Component → collector. First message is a ShipHello, then any number of
	// entries/gaps. The stream stays open for as long as the component runs.
	Ship(grpc.ClientStreamingServer[ShipMessage, ShipAck]) error
	// Which sources the collector currently holds logs for, and how far back.
	GetSources(context.Context, *Empty) (*GetSourcesResponse, error)
	// Archive of the requested logs (tar.gz: one file per source plus a manifest),
	// split into chunks — the client concatenates ExportChunk.data in order.
	Export(*ExportRequest, grpc.ServerStreamingServer[ExportChunk]) error
	mustEmbedUnimplementedLogServiceServer()
}

// UnimplementedLogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogServiceServer struct{}

func (UnimplementedLogServiceServer) Ship(grpc.ClientStreamingServer[ShipMessage, ShipAck]) error {
	return status.Errorf(codes.Unimplemented, "method Ship not implemented")
}
func (UnimplementedLogServiceServer) GetSources(context.Context, *Empty) (*GetSourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSources not implemented")
}
func (UnimplementedLogServiceServer) Export(*ExportRequest, grpc.ServerStreamingServer[ExportChunk]) error {
	return status.Errorf(codes.Unimplemented, "method Export not implemented")
}
func (UnimplementedLogServiceServer) mustEmbedUnimplementedLogServiceServer() {}
func (UnimplementedLogServiceServer) testEmbeddedByValue()                    {}

// UnsafeLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogServiceServer will
// result in compilation errors.
type UnsafeLogServiceServer interface {
	mustEmbedUnimplementedLogServiceServer()
}

func RegisterLogServiceServer(s grpc.ServiceRegistrar, srv LogServiceServer) {
	// If the following call pancis, it indicates UnimplementedLogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogService_ServiceDesc, srv)
}

func _LogService_Ship_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LogServiceServer).Ship(&grpc.GenericServerStream[ShipMessage, ShipAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LogService_ShipServer = grpc.ClientStreamingServer[ShipMessage, ShipAck]

func _LogService_GetSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).GetSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogService_GetSources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).GetSources(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_Export_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExportRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LogServiceServer).Export(m, &grpc.GenericServerStream[ExportRequest, ExportChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LogService_ExportServer = grpc.ServerStreamingServer[ExportChunk]

// LogService_ServiceDesc is the grpc.ServiceDesc for LogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hannah.LogService",
	HandlerType: (*LogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSources",
			Handler:    _LogService_GetSources_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Ship",
			Handler:       _LogService_Ship_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Export",
			Handler:       _LogService_Export_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "hannah/logging.proto",
}
