// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: hannah/satellite.proto

package hannahproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Satellite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId                string  `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Room                    string  `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`                                                    // live-reported room (UDP/proxy registration); empty if not connected
	Address                 string  `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`                                              // IP:port of the UDP satellite; empty if not connected
	DisplayName             string  `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`                   // human-readable name from Core DB (empty if not provisioned)
	RoomId                  string  `protobuf:"bytes,6,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                                  // room assigned in Core DB, "" = unassigned
	RoomDisplayName         string  `protobuf:"bytes,7,opt,name=room_display_name,json=roomDisplayName,proto3" json:"room_display_name,omitempty"`     // display name of room_id
	LastSeen                string  `protobuf:"bytes,8,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`                            // UTC "YYYY-MM-DD HH:MM:SS" from Core DB, "" = never seen
	Connected               bool    `protobuf:"varint,9,opt,name=connected,proto3" json:"connected,omitempty"`                                         // true if currently live (UDP or proxy)
	RoomMismatch            bool    `protobuf:"varint,10,opt,name=room_mismatch,json=roomMismatch,proto3" json:"room_mismatch,omitempty"`              // true if connected and live room differs from room_id
	OwnerUserId             int32   `protobuf:"varint,11,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`               // Person (User) assigned as owner in Core DB, 0 = unassigned. #31
	OwnerDisplayName        string  `protobuf:"bytes,12,opt,name=owner_display_name,json=ownerDisplayName,proto3" json:"owner_display_name,omitempty"` // display name of owner_user_id, "" if unassigned
	FirmwareVersion         string  `protobuf:"bytes,13,opt,name=firmware_version,json=firmwareVersion,proto3" json:"firmware_version,omitempty"`      // firmware_version of the satellite
	UpdateAvailable         bool    `protobuf:"varint,14,opt,name=update_available,json=updateAvailable,proto3" json:"update_available,omitempty"`     // true if the device has a new firmware available
	NewVersion              *string `protobuf:"bytes,15,opt,name=new_version,json=newVersion,proto3,oneof" json:"new_version,omitempty"`
	SmalltalkFollowupListen bool    `protobuf:"varint,16,opt,name=smalltalk_followup_listen,json=smalltalkFollowupListen,proto3" json:"smalltalk_followup_listen,omitempty"` // #158: mic reopens after a Smalltalk answer instead of waiting for wake-word/PTT again
}

func (x *Satellite) Reset() {
	*x = Satellite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_satellite_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Satellite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Satellite) ProtoMessage() {}

func (x *Satellite) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_satellite_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Satellite.ProtoReflect.Descriptor instead.
func (*Satellite) Descriptor() ([]byte, []int) {
	return file_hannah_satellite_proto_rawDescGZIP(), []int{0}
}

func (x *Satellite) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Satellite) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *Satellite) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Satellite) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Satellite) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Satellite) GetRoomDisplayName() string {
	if x != nil {
		return x.RoomDisplayName
	}
	return ""
}

func (x *Satellite) GetLastSeen() string {
	if x != nil {
		return x.LastSeen
	}
	return ""
}

func (x *Satellite) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *Satellite) GetRoomMismatch() bool {
	if x != nil {
		return x.RoomMismatch
	}
	return false
}

func (x *Satellite) GetOwnerUserId() int32 {
	if x != nil {
		return x.OwnerUserId
	}
	return 0
}

func (x *Satellite) GetOwnerDisplayName() string {
	if x != nil {
		return x.OwnerDisplayName
	}
	return ""
}

func (x *Satellite) GetFirmwareVersion() string {
	if x != nil {
		return x.FirmwareVersion
	}
	return ""
}

func (x *Satellite) GetUpdateAvailable() bool {
	if x != nil {
		return x.UpdateAvailable
	}
	return false
}

func (x *Satellite) GetNewVersion() string {
	if x != nil && x.NewVersion != nil {
		return *x.NewVersion
	}
	return ""
}

func (x *Satellite) GetSmalltalkFollowupListen() bool {
	if x != nil {
		return x.SmalltalkFollowupListen
	}
	return false
}

type GetSatellitesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Satellites []*Satellite `protobuf:"bytes,1,rep,name=satellites,proto3" json:"satellites,omitempty"`
}

func (x *GetSatellitesResponse) Reset() {
	*x = GetSatellitesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_satellite_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSatellitesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSatellitesResponse) ProtoMessage() {}

func (x *GetSatellitesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_satellite_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSatellitesResponse.ProtoReflect.Descriptor instead.
func (*GetSatellitesResponse) Descriptor() ([]byte, []int) {
	return file_hannah_satellite_proto_rawDescGZIP(), []int{1}
}

func (x *GetSatellitesResponse) GetSatellites() []*Satellite {
	if x != nil {
		return x.Satellites
	}
	return nil
}

type SetSatelliteRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId    string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	RoomId      string `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                 // "" = unassign
	RequestorId int32  `protobuf:"varint,3,opt,name=requestor_id,json=requestorId,proto3" json:"requestor_id,omitempty"` //requestor
}

func (x *SetSatelliteRoomRequest) Reset() {
	*x = SetSatelliteRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_satellite_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetSatelliteRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSatelliteRoomRequest) ProtoMessage() {}

func (x *SetSatelliteRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_satellite_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSatelliteRoomRequest.ProtoReflect.Descriptor instead.
func (*SetSatelliteRoomRequest) Descriptor() ([]byte, []int) {
	return file_hannah_satellite_proto_rawDescGZIP(), []int{2}
}

func (x *SetSatelliteRoomRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SetSatelliteRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SetSatelliteRoomRequest) GetRequestorId() int32 {
	if x != nil {
		return x.RequestorId
	}
	return 0
}

type SetSatelliteDisplayNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId    string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	RequestorId int32  `protobuf:"varint,3,opt,name=requestor_id,json=requestorId,proto3" json:"requestor_id,omitempty"` //requestor
}

func (x *SetSatelliteDisplayNameRequest) Reset() {
	*x = SetSatelliteDisplayNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_satellite_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetSatelliteDisplayNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSatelliteDisplayNameRequest) ProtoMessage() {}

func (x *SetSatelliteDisplayNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_satellite_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSatelliteDisplayNameRequest.ProtoReflect.Descriptor instead.
func (*SetSatelliteDisplayNameRequest) Descriptor() ([]byte, []int) {
	return file_hannah_satellite_proto_rawDescGZIP(), []int{3}
}

func (x *SetSatelliteDisplayNameRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SetSatelliteDisplayNameRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *SetSatelliteDisplayNameRequest) GetRequestorId() int32 {
	if x != nil {
		return x.RequestorId
	}
	return 0
}

type SetSatelliteOwnerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId    string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	UserId      int32  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                // 0 = unassign
	RequestorId int32  `protobuf:"varint,3,opt,name=requestor_id,json=requestorId,proto3" json:"requestor_id,omitempty"` //requestor
}

func (x *SetSatelliteOwnerRequest) Reset() {
	*x = SetSatelliteOwnerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_satellite_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetSatelliteOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSatelliteOwnerRequest) ProtoMessage() {}

func (x *SetSatelliteOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_satellite_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSatelliteOwnerRequest.ProtoReflect.Descriptor instead.
func (*SetSatelliteOwnerRequest) Descriptor() ([]byte, []int) {
	return file_hannah_satellite_proto_rawDescGZIP(), []int{4}
}

func (x *SetSatelliteOwnerRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SetSatelliteOwnerRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SetSatelliteOwnerRequest) GetRequestorId() int32 {
	if x != nil {
		return x.RequestorId
	}
	return 0
}

type SetSatelliteSmalltalkFollowupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId    string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Enabled     bool   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	RequestorId int32  `protobuf:"varint,3,opt,name=requestor_id,json=requestorId,proto3" json:"requestor_id,omitempty"` //requestor
}

func (x *SetSatelliteSmalltalkFollowupRequest) Reset() {
	*x = SetSatelliteSmalltalkFollowupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_satellite_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetSatelliteSmalltalkFollowupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSatelliteSmalltalkFollowupRequest) ProtoMessage() {}

func (x *SetSatelliteSmalltalkFollowupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_satellite_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSatelliteSmalltalkFollowupRequest.ProtoReflect.Descriptor instead.
func (*SetSatelliteSmalltalkFollowupRequest) Descriptor() ([]byte, []int) {
	return file_hannah_satellite_proto_rawDescGZIP(), []int{5}
}

func (x *SetSatelliteSmalltalkFollowupRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SetSatelliteSmalltalkFollowupRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SetSatelliteSmalltalkFollowupRequest) GetRequestorId() int32 {
	if x != nil {
		return x.RequestorId
	}
	return 0
}

type DeleteSatelliteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId    string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	RequestorId int32  `protobuf:"varint,2,opt,name=requestor_id,json=requestorId,proto3" json:"requestor_id,omitempty"` //requestor
}

func (x *DeleteSatelliteRequest) Reset() {
	*x = DeleteSatelliteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_satellite_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSatelliteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSatelliteRequest) ProtoMessage() {}

func (x *DeleteSatelliteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_satellite_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSatelliteRequest.ProtoReflect.Descriptor instead.
func (*DeleteSatelliteRequest) Descriptor() ([]byte, []int) {
	return file_hannah_satellite_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteSatelliteRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeleteSatelliteRequest) GetRequestorId() int32 {
	if x != nil {
		return x.RequestorId
	}
	return 0
}

var File_hannah_satellite_proto protoreflect.FileDescriptor

var file_hannah_satellite_proto_rawDesc = []byte{
	0x0a, 0x16, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2f, 0x73, 0x61, 0x74, 0x65, 0x6c, 0x6c, 0x69,
	0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68,
	0x22, 0xc6, 0x04, 0x0a, 0x09, 0x53, 0x61, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x74, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72,
	0x6f, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73,
	0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07,
	0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x64, 0x69,
	0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0f, 0x72, 0x6f, 0x6f, 0x6d, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x65, 0x6e, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x53, 0x65, 0x65, 0x6e, 0x12, 0x1c,
	0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x23, 0x0a, 0x0d,
	0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x6d, 0x69, 0x73, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0c, 0x72, 0x6f, 0x6f, 0x6d, 0x4d, 0x69, 0x73, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x12, 0x22, 0x0a, 0x0d, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x12, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x64,
	0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x66, 0x69, 0x72, 0x6d, 0x77, 0x61, 0x72, 0x65, 0x5f,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x66,
	0x69, 0x72, 0x6d, 0x77, 0x61, 0x72, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x29,
	0x0a, 0x10, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62,
	0x6c, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x24, 0x0a, 0x0b, 0x6e, 0x65, 0x77,
	0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x0a, 0x6e, 0x65, 0x77, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12,
	0x3a, 0x0a, 0x19, 0x73, 0x6d, 0x61, 0x6c, 0x6c, 0x74, 0x61, 0x6c, 0x6b, 0x5f, 0x66, 0x6f, 0x6c,
	0x6c, 0x6f, 0x77, 0x75, 0x70, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x18, 0x10, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x17, 0x73, 0x6d, 0x61, 0x6c, 0x6c, 0x74, 0x61, 0x6c, 0x6b, 0x46, 0x6f, 0x6c,
	0x6c, 0x6f, 0x77, 0x75, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x42, 0x0e, 0x0a, 0x0c, 0x5f,
	0x6e, 0x65, 0x77, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x4a, 0x04, 0x08, 0x04, 0x10,
	0x05, 0x52, 0x06, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x22, 0x4a, 0x0a, 0x15, 0x47, 0x65, 0x74,
	0x53, 0x61, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x31, 0x0a, 0x0a, 0x73, 0x61, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x74, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e,
	0x53, 0x61, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x74, 0x65, 0x52, 0x0a, 0x73, 0x61, 0x74, 0x65, 0x6c,
	0x6c, 0x69, 0x74, 0x65, 0x73, 0x22, 0x72, 0x0a, 0x17, 0x53, 0x65, 0x74, 0x53, 0x61, 0x74, 0x65,
	0x6c, 0x6c, 0x69, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x22, 0x83, 0x01, 0x0a, 0x1e, 0x53, 0x65,
	0x74, 0x53, 0x61, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x74, 0x65, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73,
	0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x22,
	0x73, 0x0a, 0x18, 0x53, 0x65, 0x74, 0x53, 0x61, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x74, 0x65, 0x4f,
	0x77, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x6f, 0x72, 0x49, 0x64, 0x22, 0x80, 0x01, 0x0a, 0x24, 0x53, 0x65, 0x74, 0x53, 0x61, 0x74, 0x65,
	0x6c, 0x6c, 0x69, 0x74, 0x65, 0x53, 0x6d, 0x61, 0x6c, 0x6c, 0x74, 0x61, 0x6c, 0x6b, 0x46, 0x6f,
	0x6c, 0x6c, 0x6f, 0x77, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e,
	0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x6f,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x22, 0x58, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x53, 0x61, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x21,
	0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x49,
	0x64, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x4e, 0x75, 0x72, 0x50, 0x65, 0x63, 0x68, 0x2f, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2d, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x6f, 0x3b, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hannah_satellite_proto_rawDescOnce sync.Once
	file_hannah_satellite_proto_rawDescData = file_hannah_satellite_proto_rawDesc
)

func file_hannah_satellite_proto_rawDescGZIP() []byte {
	file_hannah_satellite_proto_rawDescOnce.Do(func() {
		file_hannah_satellite_proto_rawDescData = protoimpl.X.CompressGZIP(file_hannah_satellite_proto_rawDescData)
	})
	return file_hannah_satellite_proto_rawDescData
}

var file_hannah_satellite_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_hannah_satellite_proto_goTypes = []any{
	(*Satellite)(nil),                            // 0: hannah.Satellite
	(*GetSatellitesResponse)(nil),                // 1: hannah.GetSatellitesResponse
	(*SetSatelliteRoomRequest)(nil),              // 2: hannah.SetSatelliteRoomRequest
	(*SetSatelliteDisplayNameRequest)(nil),       // 3: hannah.SetSatelliteDisplayNameRequest
	(*SetSatelliteOwnerRequest)(nil),             // 4: hannah.SetSatelliteOwnerRequest
	(*SetSatelliteSmalltalkFollowupRequest)(nil), // 5: hannah.SetSatelliteSmalltalkFollowupRequest
	(*DeleteSatelliteRequest)(nil),               // 6: hannah.DeleteSatelliteRequest
}
var file_hannah_satellite_proto_depIdxs = []int32{
	0, // 0: hannah.GetSatellitesResponse.satellites:type_name -> hannah.Satellite
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_hannah_satellite_proto_init() }
func file_hannah_satellite_proto_init() {
	if File_hannah_satellite_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hannah_satellite_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Satellite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_satellite_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetSatellitesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_satellite_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SetSatelliteRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_satellite_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*SetSatelliteDisplayNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_satellite_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*SetSatelliteOwnerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_satellite_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*SetSatelliteSmalltalkFollowupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_satellite_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteSatelliteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_hannah_satellite_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hannah_satellite_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hannah_satellite_proto_goTypes,
		DependencyIndexes: file_hannah_satellite_proto_depIdxs,
		MessageInfos:      file_hannah_satellite_proto_msgTypes,
	}.Build()
	File_hannah_satellite_proto = out.File
	file_hannah_satellite_proto_rawDesc = nil
	file_hannah_satellite_proto_goTypes = nil
	file_hannah_satellite_proto_depIdxs = nil
}
