// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: satellite_proxy.proto

package hannahproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Sent by the proxy periodically to keep the RegisterProxy stream alive.
type ProxyHeartbeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProxyId string `protobuf:"bytes,1,opt,name=proxy_id,json=proxyId,proto3" json:"proxy_id,omitempty"` // human-readable identifier, e.g. "hannah-proxy-living-room"
	// UDP address the proxy is listening on for satellite connections.
	// When set, Hannah publishes this address to the discovery topic so
	// satellites connect to the proxy instead of Hannah's own UDP server.
	UdpHost string `protobuf:"bytes,2,opt,name=udp_host,json=udpHost,proto3" json:"udp_host,omitempty"`  // advertise host, e.g. "192.168.8.5"
	UdpPort int32  `protobuf:"varint,3,opt,name=udp_port,json=udpPort,proto3" json:"udp_port,omitempty"` // UDP port, e.g. 7775
}

func (x *ProxyHeartbeat) Reset() {
	*x = ProxyHeartbeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_satellite_proxy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProxyHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyHeartbeat) ProtoMessage() {}

func (x *ProxyHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proxy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyHeartbeat.ProtoReflect.Descriptor instead.
func (*ProxyHeartbeat) Descriptor() ([]byte, []int) {
	return file_satellite_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *ProxyHeartbeat) GetProxyId() string {
	if x != nil {
		return x.ProxyId
	}
	return ""
}

func (x *ProxyHeartbeat) GetUdpHost() string {
	if x != nil {
		return x.UdpHost
	}
	return ""
}

func (x *ProxyHeartbeat) GetUdpPort() int32 {
	if x != nil {
		return x.UdpPort
	}
	return 0
}

// Sent by Hannah to the proxy over the RegisterProxy stream.
type ProxyCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Command:
	//
	//	*ProxyCommand_Ack
	//	*ProxyCommand_PlayAudio
	Command isProxyCommand_Command `protobuf_oneof:"command"`
}

func (x *ProxyCommand) Reset() {
	*x = ProxyCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_satellite_proxy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProxyCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyCommand) ProtoMessage() {}

func (x *ProxyCommand) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proxy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyCommand.ProtoReflect.Descriptor instead.
func (*ProxyCommand) Descriptor() ([]byte, []int) {
	return file_satellite_proxy_proto_rawDescGZIP(), []int{1}
}

func (m *ProxyCommand) GetCommand() isProxyCommand_Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (x *ProxyCommand) GetAck() *ProxyAck {
	if x, ok := x.GetCommand().(*ProxyCommand_Ack); ok {
		return x.Ack
	}
	return nil
}

func (x *ProxyCommand) GetPlayAudio() *PlayAudioCommand {
	if x, ok := x.GetCommand().(*ProxyCommand_PlayAudio); ok {
		return x.PlayAudio
	}
	return nil
}

type isProxyCommand_Command interface {
	isProxyCommand_Command()
}

type ProxyCommand_Ack struct {
	Ack *ProxyAck `protobuf:"bytes,1,opt,name=ack,proto3,oneof"` // initial confirmation when stream is established
}

type ProxyCommand_PlayAudio struct {
	PlayAudio *PlayAudioCommand `protobuf:"bytes,2,opt,name=play_audio,json=playAudio,proto3,oneof"` // Hannah wants the proxy to play TTS on a satellite
}

func (*ProxyCommand_Ack) isProxyCommand_Command() {}

func (*ProxyCommand_PlayAudio) isProxyCommand_Command() {}

// Sent once by Hannah after RegisterProxy stream is established.
type ProxyAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UdpDisabled bool   `protobuf:"varint,1,opt,name=udp_disabled,json=udpDisabled,proto3" json:"udp_disabled,omitempty"` // true = Hannah has disabled its own UDP server
	Message     string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                             // human-readable status, e.g. "UDP server stopped"
}

func (x *ProxyAck) Reset() {
	*x = ProxyAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_satellite_proxy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProxyAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyAck) ProtoMessage() {}

func (x *ProxyAck) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proxy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyAck.ProtoReflect.Descriptor instead.
func (*ProxyAck) Descriptor() ([]byte, []int) {
	return file_satellite_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *ProxyAck) GetUdpDisabled() bool {
	if x != nil {
		return x.UdpDisabled
	}
	return false
}

func (x *ProxyAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Hannah instructs the proxy to play TTS audio on a specific satellite.
// Used for announcements and other server-initiated audio.
// For streaming: Hannah sends multiple PlayAudioCommands with chunks of PCM.
// is_last=true on the final chunk signals the proxy to send tts_end to the satellite.
type PlayAudioCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId   string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`        // satellite device name (as registered via UDP or proxy)
	AudioPcm   []byte `protobuf:"bytes,2,opt,name=audio_pcm,json=audioPcm,proto3" json:"audio_pcm,omitempty"`        // raw PCM, 16-bit signed mono
	SampleRate int32  `protobuf:"varint,3,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"` // e.g. 24000 (Azure) or 16000 (Piper)
	IsLast     bool   `protobuf:"varint,4,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`             // true on the last chunk of a TTS response
}

func (x *PlayAudioCommand) Reset() {
	*x = PlayAudioCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_satellite_proxy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayAudioCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayAudioCommand) ProtoMessage() {}

func (x *PlayAudioCommand) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proxy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayAudioCommand.ProtoReflect.Descriptor instead.
func (*PlayAudioCommand) Descriptor() ([]byte, []int) {
	return file_satellite_proxy_proto_rawDescGZIP(), []int{3}
}

func (x *PlayAudioCommand) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *PlayAudioCommand) GetAudioPcm() []byte {
	if x != nil {
		return x.AudioPcm
	}
	return nil
}

func (x *PlayAudioCommand) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *PlayAudioCommand) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

// Sent by the proxy when a satellite has finished recording an utterance.
type SubmitSatelliteAudioRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId   string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`        // satellite device name
	Room       string `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`                                // room name (from proxy registration / config)
	AudioPcm   []byte `protobuf:"bytes,3,opt,name=audio_pcm,json=audioPcm,proto3" json:"audio_pcm,omitempty"`        // raw PCM, 16-bit signed mono, 16000 Hz
	SampleRate int32  `protobuf:"varint,4,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"` // sample rate of the audio (typically 16000)
	// Optional: speaker identity (Hannah users.id) provided by an upstream speaker-ID service.
	// Empty = anonymous (Hannah treats as unknown user).
	SpeakerUserId string `protobuf:"bytes,5,opt,name=speaker_user_id,json=speakerUserId,proto3" json:"speaker_user_id,omitempty"`
}

func (x *SubmitSatelliteAudioRequest) Reset() {
	*x = SubmitSatelliteAudioRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_satellite_proxy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitSatelliteAudioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitSatelliteAudioRequest) ProtoMessage() {}

func (x *SubmitSatelliteAudioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proxy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitSatelliteAudioRequest.ProtoReflect.Descriptor instead.
func (*SubmitSatelliteAudioRequest) Descriptor() ([]byte, []int) {
	return file_satellite_proxy_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitSatelliteAudioRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SubmitSatelliteAudioRequest) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *SubmitSatelliteAudioRequest) GetAudioPcm() []byte {
	if x != nil {
		return x.AudioPcm
	}
	return nil
}

func (x *SubmitSatelliteAudioRequest) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *SubmitSatelliteAudioRequest) GetSpeakerUserId() string {
	if x != nil {
		return x.SpeakerUserId
	}
	return ""
}

type SubmitSatelliteAudioResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transcript string `protobuf:"bytes,1,opt,name=transcript,proto3" json:"transcript,omitempty"`                    // STT result
	Answer     string `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`                            // text answer from Hannah
	IntentName string `protobuf:"bytes,3,opt,name=intent_name,json=intentName,proto3" json:"intent_name,omitempty"`  // e.g. "TurnOn", "CarQuery", "Unknown"
	AudioPcm   []byte `protobuf:"bytes,4,opt,name=audio_pcm,json=audioPcm,proto3" json:"audio_pcm,omitempty"`        // TTS response as raw PCM, 16-bit signed mono
	SampleRate int32  `protobuf:"varint,5,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"` // sample rate of audio_pcm
}

func (x *SubmitSatelliteAudioResponse) Reset() {
	*x = SubmitSatelliteAudioResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_satellite_proxy_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitSatelliteAudioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitSatelliteAudioResponse) ProtoMessage() {}

func (x *SubmitSatelliteAudioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proxy_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitSatelliteAudioResponse.ProtoReflect.Descriptor instead.
func (*SubmitSatelliteAudioResponse) Descriptor() ([]byte, []int) {
	return file_satellite_proxy_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitSatelliteAudioResponse) GetTranscript() string {
	if x != nil {
		return x.Transcript
	}
	return ""
}

func (x *SubmitSatelliteAudioResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *SubmitSatelliteAudioResponse) GetIntentName() string {
	if x != nil {
		return x.IntentName
	}
	return ""
}

func (x *SubmitSatelliteAudioResponse) GetAudioPcm() []byte {
	if x != nil {
		return x.AudioPcm
	}
	return nil
}

func (x *SubmitSatelliteAudioResponse) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

type SatelliteRegistration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // satellite device_id (== eFuse MAC since v0.34), e.g. "e072a1d01adc"
	Address  string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`                   // IP of the UDP satellite as seen by the proxy, e.g. "192.168.8.42"
	Seed     string `protobuf:"bytes,5,opt,name=seed,proto3" json:"seed,omitempty"`                         // one-time pairing token from NVS (empty after successful pairing)
}

func (x *SatelliteRegistration) Reset() {
	*x = SatelliteRegistration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_satellite_proxy_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SatelliteRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SatelliteRegistration) ProtoMessage() {}

func (x *SatelliteRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proxy_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SatelliteRegistration.ProtoReflect.Descriptor instead.
func (*SatelliteRegistration) Descriptor() ([]byte, []int) {
	return file_satellite_proxy_proto_rawDescGZIP(), []int{6}
}

func (x *SatelliteRegistration) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SatelliteRegistration) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SatelliteRegistration) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

var File_satellite_proxy_proto protoreflect.FileDescriptor

var file_satellite_proxy_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x61, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x74, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x78,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x22,
	0x61, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x75, 0x64, 0x70, 0x5f, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x75, 0x64, 0x70, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x64, 0x70, 0x5f, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x75, 0x64, 0x70, 0x50, 0x6f,
	0x72, 0x74, 0x22, 0x7a, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x12, 0x24, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x41, 0x63,
	0x6b, 0x48, 0x00, 0x52, 0x03, 0x61, 0x63, 0x6b, 0x12, 0x39, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79,
	0x5f, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x68,
	0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x41, 0x75,
	0x64, 0x69, 0x6f, 0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x47,
	0x0a, 0x08, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x41, 0x63, 0x6b, 0x12, 0x21, 0x0a, 0x0c, 0x75, 0x64,
	0x70, 0x5f, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0b, 0x75, 0x64, 0x70, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x86, 0x01, 0x0a, 0x10, 0x50, 0x6c, 0x61, 0x79,
	0x41, 0x75, 0x64, 0x69, 0x6f, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x75, 0x64,
	0x69, 0x6f, 0x5f, 0x70, 0x63, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x61, 0x75,
	0x64, 0x69, 0x6f, 0x50, 0x63, 0x6d, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x52, 0x61, 0x74, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x6c, 0x61,
	0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x4c, 0x61, 0x73, 0x74,
	0x22, 0xb4, 0x01, 0x0a, 0x1b, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x53, 0x61, 0x74, 0x65, 0x6c,
	0x6c, 0x69, 0x74, 0x65, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6f,
	0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x5f, 0x70, 0x63, 0x6d, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x50, 0x63, 0x6d, 0x12, 0x1f,
	0x0a, 0x0b, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x61, 0x74, 0x65, 0x12,
	0x26, 0x0a, 0x0f, 0x73, 0x70, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x70, 0x65, 0x61, 0x6b, 0x65,
	0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0xb5, 0x01, 0x0a, 0x1c, 0x53, 0x75, 0x62, 0x6d,
	0x69, 0x74, 0x53, 0x61, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x74, 0x65, 0x41, 0x75, 0x64, 0x69, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x5f, 0x70, 0x63, 0x6d, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x50, 0x63, 0x6d, 0x12, 0x1f,
	0x0a, 0x0b, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x61, 0x74, 0x65, 0x22,
	0x7c, 0x0a, 0x15, 0x53, 0x61, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x74, 0x65, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x65, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73,
	0x65, 0x65, 0x64, 0x4a, 0x04, 0x08, 0x02, 0x10, 0x03, 0x4a, 0x04, 0x08, 0x04, 0x10, 0x05, 0x52,
	0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x52, 0x06, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x42, 0x30, 0x5a,
	0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4e, 0x75, 0x72, 0x50,
	0x65, 0x63, 0x68, 0x2f, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2d, 0x67, 0x6f, 0x3b, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_satellite_proxy_proto_rawDescOnce sync.Once
	file_satellite_proxy_proto_rawDescData = file_satellite_proxy_proto_rawDesc
)

func file_satellite_proxy_proto_rawDescGZIP() []byte {
	file_satellite_proxy_proto_rawDescOnce.Do(func() {
		file_satellite_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(file_satellite_proxy_proto_rawDescData)
	})
	return file_satellite_proxy_proto_rawDescData
}

var file_satellite_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_satellite_proxy_proto_goTypes = []any{
	(*ProxyHeartbeat)(nil),               // 0: hannah.ProxyHeartbeat
	(*ProxyCommand)(nil),                 // 1: hannah.ProxyCommand
	(*ProxyAck)(nil),                     // 2: hannah.ProxyAck
	(*PlayAudioCommand)(nil),             // 3: hannah.PlayAudioCommand
	(*SubmitSatelliteAudioRequest)(nil),  // 4: hannah.SubmitSatelliteAudioRequest
	(*SubmitSatelliteAudioResponse)(nil), // 5: hannah.SubmitSatelliteAudioResponse
	(*SatelliteRegistration)(nil),        // 6: hannah.SatelliteRegistration
}
var file_satellite_proxy_proto_depIdxs = []int32{
	2, // 0: hannah.ProxyCommand.ack:type_name -> hannah.ProxyAck
	3, // 1: hannah.ProxyCommand.play_audio:type_name -> hannah.PlayAudioCommand
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_satellite_proxy_proto_init() }
func file_satellite_proxy_proto_init() {
	if File_satellite_proxy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_satellite_proxy_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ProxyHeartbeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_satellite_proxy_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ProxyCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_satellite_proxy_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ProxyAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_satellite_proxy_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*PlayAudioCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_satellite_proxy_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*SubmitSatelliteAudioRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_satellite_proxy_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*SubmitSatelliteAudioResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_satellite_proxy_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*SatelliteRegistration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_satellite_proxy_proto_msgTypes[1].OneofWrappers = []any{
		(*ProxyCommand_Ack)(nil),
		(*ProxyCommand_PlayAudio)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_satellite_proxy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_satellite_proxy_proto_goTypes,
		DependencyIndexes: file_satellite_proxy_proto_depIdxs,
		MessageInfos:      file_satellite_proxy_proto_msgTypes,
	}.Build()
	File_satellite_proxy_proto = out.File
	file_satellite_proxy_proto_rawDesc = nil
	file_satellite_proxy_proto_goTypes = nil
	file_satellite_proxy_proto_depIdxs = nil
}
