// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: speaker_enrollment.proto

package hannahproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrollVoiceprintRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`              // Hannah user this voice sample belongs to (users.id, stable)
	AudioPcm   []byte `protobuf:"bytes,2,opt,name=audio_pcm,json=audioPcm,proto3" json:"audio_pcm,omitempty"`        // raw PCM, 16-bit signed mono
	SampleRate int32  `protobuf:"varint,3,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"` // e.g. 16000
}

func (x *EnrollVoiceprintRequest) Reset() {
	*x = EnrollVoiceprintRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_speaker_enrollment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnrollVoiceprintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollVoiceprintRequest) ProtoMessage() {}

func (x *EnrollVoiceprintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_speaker_enrollment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollVoiceprintRequest.ProtoReflect.Descriptor instead.
func (*EnrollVoiceprintRequest) Descriptor() ([]byte, []int) {
	return file_speaker_enrollment_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollVoiceprintRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EnrollVoiceprintRequest) GetAudioPcm() []byte {
	if x != nil {
		return x.AudioPcm
	}
	return nil
}

func (x *EnrollVoiceprintRequest) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

var File_speaker_enrollment_proto protoreflect.FileDescriptor

var file_speaker_enrollment_proto_rawDesc = []byte{
	0x0a, 0x18, 0x73, 0x70, 0x65, 0x61, 0x6b, 0x65, 0x72, 0x5f, 0x65, 0x6e, 0x72, 0x6f, 0x6c, 0x6c,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x68, 0x61, 0x6e, 0x6e,
	0x61, 0x68, 0x22, 0x70, 0x0a, 0x17, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x56, 0x6f, 0x69, 0x63,
	0x65, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x5f,
	0x70, 0x63, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x61, 0x75, 0x64, 0x69, 0x6f,
	0x50, 0x63, 0x6d, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x72, 0x61,
	0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x52, 0x61, 0x74, 0x65, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x4e, 0x75, 0x72, 0x50, 0x65, 0x63, 0x68, 0x2f, 0x68, 0x61, 0x6e, 0x6e, 0x61,
	0x68, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x6f, 0x3b, 0x68, 0x61, 0x6e, 0x6e, 0x61,
	0x68, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_speaker_enrollment_proto_rawDescOnce sync.Once
	file_speaker_enrollment_proto_rawDescData = file_speaker_enrollment_proto_rawDesc
)

func file_speaker_enrollment_proto_rawDescGZIP() []byte {
	file_speaker_enrollment_proto_rawDescOnce.Do(func() {
		file_speaker_enrollment_proto_rawDescData = protoimpl.X.CompressGZIP(file_speaker_enrollment_proto_rawDescData)
	})
	return file_speaker_enrollment_proto_rawDescData
}

var file_speaker_enrollment_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_speaker_enrollment_proto_goTypes = []any{
	(*EnrollVoiceprintRequest)(nil), // 0: hannah.EnrollVoiceprintRequest
}
var file_speaker_enrollment_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_speaker_enrollment_proto_init() }
func file_speaker_enrollment_proto_init() {
	if File_speaker_enrollment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_speaker_enrollment_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*EnrollVoiceprintRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_speaker_enrollment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_speaker_enrollment_proto_goTypes,
		DependencyIndexes: file_speaker_enrollment_proto_depIdxs,
		MessageInfos:      file_speaker_enrollment_proto_msgTypes,
	}.Build()
	File_speaker_enrollment_proto = out.File
	file_speaker_enrollment_proto_rawDesc = nil
	file_speaker_enrollment_proto_goTypes = nil
	file_speaker_enrollment_proto_depIdxs = nil
}
