// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: timer_service.proto

package hannahproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Sent by Hannah Core over the TimerConnect stream.
type TimerCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Command:
	//
	//	*TimerCommand_Create
	//	*TimerCommand_Cancel
	//	*TimerCommand_List
	//	*TimerCommand_Ready
	//	*TimerCommand_NotReady
	Command isTimerCommand_Command `protobuf_oneof:"command"`
}

func (x *TimerCommand) Reset() {
	*x = TimerCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timer_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimerCommand) ProtoMessage() {}

func (x *TimerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_timer_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimerCommand.ProtoReflect.Descriptor instead.
func (*TimerCommand) Descriptor() ([]byte, []int) {
	return file_timer_service_proto_rawDescGZIP(), []int{0}
}

func (m *TimerCommand) GetCommand() isTimerCommand_Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (x *TimerCommand) GetCreate() *TimerCreate {
	if x, ok := x.GetCommand().(*TimerCommand_Create); ok {
		return x.Create
	}
	return nil
}

func (x *TimerCommand) GetCancel() *TimerCancel {
	if x, ok := x.GetCommand().(*TimerCommand_Cancel); ok {
		return x.Cancel
	}
	return nil
}

func (x *TimerCommand) GetList() *TimerListRequest {
	if x, ok := x.GetCommand().(*TimerCommand_List); ok {
		return x.List
	}
	return nil
}

func (x *TimerCommand) GetReady() *TimerReady {
	if x, ok := x.GetCommand().(*TimerCommand_Ready); ok {
		return x.Ready
	}
	return nil
}

func (x *TimerCommand) GetNotReady() *TimerNotReady {
	if x, ok := x.GetCommand().(*TimerCommand_NotReady); ok {
		return x.NotReady
	}
	return nil
}

type isTimerCommand_Command interface {
	isTimerCommand_Command()
}

type TimerCommand_Create struct {
	Create *TimerCreate `protobuf:"bytes,1,opt,name=create,proto3,oneof"` // create a new timer
}

type TimerCommand_Cancel struct {
	Cancel *TimerCancel `protobuf:"bytes,2,opt,name=cancel,proto3,oneof"` // cancel an existing timer
}

type TimerCommand_List struct {
	List *TimerListRequest `protobuf:"bytes,3,opt,name=list,proto3,oneof"` // request current timer list
}

type TimerCommand_Ready struct {
	Ready *TimerReady `protobuf:"bytes,4,opt,name=ready,proto3,oneof"` // Hannah is ready to receive pending fired events
}

type TimerCommand_NotReady struct {
	NotReady *TimerNotReady `protobuf:"bytes,5,opt,name=not_ready,json=notReady,proto3,oneof"` // Hannah is temporarily unable to process timer firings
}

func (*TimerCommand_Create) isTimerCommand_Command() {}

func (*TimerCommand_Cancel) isTimerCommand_Command() {}

func (*TimerCommand_List) isTimerCommand_Command() {}

func (*TimerCommand_Ready) isTimerCommand_Command() {}

func (*TimerCommand_NotReady) isTimerCommand_Command() {}

// Hannah signals that she is ready to receive queued TimerFired events.
// Sent after startup once ioBroker states are loaded. The service flushes
// any TimerFired events that occurred while Hannah was offline, in order.
type TimerReady struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TimerReady) Reset() {
	*x = TimerReady{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timer_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimerReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimerReady) ProtoMessage() {}

func (x *TimerReady) ProtoReflect() protoreflect.Message {
	mi := &file_timer_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimerReady.ProtoReflect.Descriptor instead.
func (*TimerReady) Descriptor() ([]byte, []int) {
	return file_timer_service_proto_rawDescGZIP(), []int{1}
}

// Hannah signals a temporary degraded state — the Timer Service should hold
// any TimerFired events in its queue until a subsequent TimerReady is received.
// Hannah sends this when core subsystems are unavailable (e.g. ioBroker disconnected).
type TimerNotReady struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason *string `protobuf:"bytes,1,opt,name=reason,proto3,oneof" json:"reason,omitempty"` // human-readable reason, e.g. "ioBroker disconnected"
}

func (x *TimerNotReady) Reset() {
	*x = TimerNotReady{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timer_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimerNotReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimerNotReady) ProtoMessage() {}

func (x *TimerNotReady) ProtoReflect() protoreflect.Message {
	mi := &file_timer_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimerNotReady.ProtoReflect.Descriptor instead.
func (*TimerNotReady) Descriptor() ([]byte, []int) {
	return file_timer_service_proto_rawDescGZIP(), []int{2}
}

func (x *TimerNotReady) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

// Hannah instructs the timer service to create a new timer.
type TimerCreate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimerId  string            `protobuf:"bytes,1,opt,name=timer_id,json=timerId,proto3" json:"timer_id,omitempty"`                                                                            // UUID assigned by Hannah
	Label    string            `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`                                                                                               // human-readable label, e.g. "Spazieren gehen"
	FireAt   int64             `protobuf:"varint,3,opt,name=fire_at,json=fireAt,proto3" json:"fire_at,omitempty"`                                                                              // Unix timestamp (seconds) when to fire
	Metadata map[string]string `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // opaque to the Timer Service — e.g. "room", "roomie_id", "trigger_id"
}

func (x *TimerCreate) Reset() {
	*x = TimerCreate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timer_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimerCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimerCreate) ProtoMessage() {}

func (x *TimerCreate) ProtoReflect() protoreflect.Message {
	mi := &file_timer_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimerCreate.ProtoReflect.Descriptor instead.
func (*TimerCreate) Descriptor() ([]byte, []int) {
	return file_timer_service_proto_rawDescGZIP(), []int{3}
}

func (x *TimerCreate) GetTimerId() string {
	if x != nil {
		return x.TimerId
	}
	return ""
}

func (x *TimerCreate) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *TimerCreate) GetFireAt() int64 {
	if x != nil {
		return x.FireAt
	}
	return 0
}

func (x *TimerCreate) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Hannah instructs the timer service to cancel a timer.
type TimerCancel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimerId string `protobuf:"bytes,1,opt,name=timer_id,json=timerId,proto3" json:"timer_id,omitempty"`
}

func (x *TimerCancel) Reset() {
	*x = TimerCancel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timer_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimerCancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimerCancel) ProtoMessage() {}

func (x *TimerCancel) ProtoReflect() protoreflect.Message {
	mi := &file_timer_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimerCancel.ProtoReflect.Descriptor instead.
func (*TimerCancel) Descriptor() ([]byte, []int) {
	return file_timer_service_proto_rawDescGZIP(), []int{4}
}

func (x *TimerCancel) GetTimerId() string {
	if x != nil {
		return x.TimerId
	}
	return ""
}

// Hannah requests the current list of active timers (e.g. "welche Timer habe ich?").
type TimerListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TimerListRequest) Reset() {
	*x = TimerListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timer_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimerListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimerListRequest) ProtoMessage() {}

func (x *TimerListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_timer_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimerListRequest.ProtoReflect.Descriptor instead.
func (*TimerListRequest) Descriptor() ([]byte, []int) {
	return file_timer_service_proto_rawDescGZIP(), []int{5}
}

// Sent by the Timer Service over the TimerConnect stream.
type TimerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*TimerMessage_Ack
	//	*TimerMessage_Fired
	//	*TimerMessage_List
	Payload isTimerMessage_Payload `protobuf_oneof:"payload"`
}

func (x *TimerMessage) Reset() {
	*x = TimerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timer_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimerMessage) ProtoMessage() {}

func (x *TimerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_timer_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimerMessage.ProtoReflect.Descriptor instead.
func (*TimerMessage) Descriptor() ([]byte, []int) {
	return file_timer_service_proto_rawDescGZIP(), []int{6}
}

func (m *TimerMessage) GetPayload() isTimerMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *TimerMessage) GetAck() *TimerAck {
	if x, ok := x.GetPayload().(*TimerMessage_Ack); ok {
		return x.Ack
	}
	return nil
}

func (x *TimerMessage) GetFired() *TimerFired {
	if x, ok := x.GetPayload().(*TimerMessage_Fired); ok {
		return x.Fired
	}
	return nil
}

func (x *TimerMessage) GetList() *TimerListResponse {
	if x, ok := x.GetPayload().(*TimerMessage_List); ok {
		return x.List
	}
	return nil
}

type isTimerMessage_Payload interface {
	isTimerMessage_Payload()
}

type TimerMessage_Ack struct {
	Ack *TimerAck `protobuf:"bytes,1,opt,name=ack,proto3,oneof"` // initial confirmation when stream is established
}

type TimerMessage_Fired struct {
	Fired *TimerFired `protobuf:"bytes,2,opt,name=fired,proto3,oneof"` // a timer has expired
}

type TimerMessage_List struct {
	List *TimerListResponse `protobuf:"bytes,3,opt,name=list,proto3,oneof"` // response to TimerListRequest
}

func (*TimerMessage_Ack) isTimerMessage_Payload() {}

func (*TimerMessage_Fired) isTimerMessage_Payload() {}

func (*TimerMessage_List) isTimerMessage_Payload() {}

// Sent once by the Timer Service after TimerConnect stream is established.
type TimerAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message      string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`                                // human-readable status
	ActiveTimers int32  `protobuf:"varint,2,opt,name=active_timers,json=activeTimers,proto3" json:"active_timers,omitempty"` // number of timers currently tracked
}

func (x *TimerAck) Reset() {
	*x = TimerAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timer_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimerAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimerAck) ProtoMessage() {}

func (x *TimerAck) ProtoReflect() protoreflect.Message {
	mi := &file_timer_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimerAck.ProtoReflect.Descriptor instead.
func (*TimerAck) Descriptor() ([]byte, []int) {
	return file_timer_service_proto_rawDescGZIP(), []int{7}
}

func (x *TimerAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TimerAck) GetActiveTimers() int32 {
	if x != nil {
		return x.ActiveTimers
	}
	return 0
}

// Timer Service notifies Hannah that a timer has expired.
type TimerFired struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimerId  string            `protobuf:"bytes,1,opt,name=timer_id,json=timerId,proto3" json:"timer_id,omitempty"`
	Label    string            `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`                                                                                               // convenience copy for logging
	Metadata map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // echoed verbatim from TimerCreate
}

func (x *TimerFired) Reset() {
	*x = TimerFired{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timer_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimerFired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimerFired) ProtoMessage() {}

func (x *TimerFired) ProtoReflect() protoreflect.Message {
	mi := &file_timer_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimerFired.ProtoReflect.Descriptor instead.
func (*TimerFired) Descriptor() ([]byte, []int) {
	return file_timer_service_proto_rawDescGZIP(), []int{8}
}

func (x *TimerFired) GetTimerId() string {
	if x != nil {
		return x.TimerId
	}
	return ""
}

func (x *TimerFired) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *TimerFired) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Response to TimerListRequest — used for sync and "welche Timer habe ich?" queries.
type TimerListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timers []*TimerInfo `protobuf:"bytes,1,rep,name=timers,proto3" json:"timers,omitempty"`
}

func (x *TimerListResponse) Reset() {
	*x = TimerListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timer_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimerListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimerListResponse) ProtoMessage() {}

func (x *TimerListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_timer_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimerListResponse.ProtoReflect.Descriptor instead.
func (*TimerListResponse) Descriptor() ([]byte, []int) {
	return file_timer_service_proto_rawDescGZIP(), []int{9}
}

func (x *TimerListResponse) GetTimers() []*TimerInfo {
	if x != nil {
		return x.Timers
	}
	return nil
}

type TimerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimerId  string            `protobuf:"bytes,1,opt,name=timer_id,json=timerId,proto3" json:"timer_id,omitempty"`
	Label    string            `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	FireAt   int64             `protobuf:"varint,3,opt,name=fire_at,json=fireAt,proto3" json:"fire_at,omitempty"` // Unix timestamp (seconds)
	Metadata map[string]string `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *TimerInfo) Reset() {
	*x = TimerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timer_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimerInfo) ProtoMessage() {}

func (x *TimerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_timer_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimerInfo.ProtoReflect.Descriptor instead.
func (*TimerInfo) Descriptor() ([]byte, []int) {
	return file_timer_service_proto_rawDescGZIP(), []int{10}
}

func (x *TimerInfo) GetTimerId() string {
	if x != nil {
		return x.TimerId
	}
	return ""
}

func (x *TimerInfo) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *TimerInfo) GetFireAt() int64 {
	if x != nil {
		return x.FireAt
	}
	return 0
}

func (x *TimerInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_timer_service_proto protoreflect.FileDescriptor

var file_timer_service_proto_rawDesc = []byte{
	0x0a, 0x13, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x22, 0x89, 0x02,
	0x0a, 0x0c, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x2d,
	0x0a, 0x06, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x06, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x2d, 0x0a,
	0x06, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x43, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x48, 0x00, 0x52, 0x06, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x12, 0x2e, 0x0a, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x68, 0x61, 0x6e,
	0x6e, 0x61, 0x68, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x05,
	0x72, 0x65, 0x61, 0x64, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x68, 0x61,
	0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x61, 0x64, 0x79, 0x48,
	0x00, 0x52, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x12, 0x34, 0x0a, 0x09, 0x6e, 0x6f, 0x74, 0x5f,
	0x72, 0x65, 0x61, 0x64, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x68, 0x61,
	0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x52, 0x65, 0x61,
	0x64, 0x79, 0x48, 0x00, 0x52, 0x08, 0x6e, 0x6f, 0x74, 0x52, 0x65, 0x61, 0x64, 0x79, 0x42, 0x09,
	0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x0c, 0x0a, 0x0a, 0x54, 0x69, 0x6d,
	0x65, 0x72, 0x52, 0x65, 0x61, 0x64, 0x79, 0x22, 0x37, 0x0a, 0x0d, 0x54, 0x69, 0x6d, 0x65, 0x72,
	0x4e, 0x6f, 0x74, 0x52, 0x65, 0x61, 0x64, 0x79, 0x12, 0x1b, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x22, 0xf0, 0x01, 0x0a, 0x0b, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x12, 0x19, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x61, 0x62, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65,
	0x6c, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69, 0x72, 0x65, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x66, 0x69, 0x72, 0x65, 0x41, 0x74, 0x12, 0x3d, 0x0a, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x68,
	0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x3b, 0x0a, 0x0d, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x4a, 0x04, 0x08, 0x04, 0x10, 0x05, 0x4a, 0x04, 0x08, 0x05,
	0x10, 0x06, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x52, 0x09, 0x72, 0x6f, 0x6f, 0x6d, 0x69, 0x65,
	0x5f, 0x69, 0x64, 0x22, 0x28, 0x0a, 0x0b, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x43, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x22, 0x12, 0x0a,
	0x10, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x9c, 0x01, 0x0a, 0x0c, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x24, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x41, 0x63,
	0x6b, 0x48, 0x00, 0x52, 0x03, 0x61, 0x63, 0x6b, 0x12, 0x2a, 0x0a, 0x05, 0x66, 0x69, 0x72, 0x65,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x46, 0x69, 0x72, 0x65, 0x64, 0x48, 0x00, 0x52, 0x05, 0x66,
	0x69, 0x72, 0x65, 0x64, 0x12, 0x2f, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x22, 0x49, 0x0a, 0x08, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x41, 0x63, 0x6b, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x73, 0x22, 0xb8, 0x01, 0x0a, 0x0a,
	0x54, 0x69, 0x6d, 0x65, 0x72, 0x46, 0x69, 0x72, 0x65, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x69,
	0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x69,
	0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x3c, 0x0a, 0x08, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e,
	0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x46, 0x69, 0x72, 0x65,
	0x64, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x3b, 0x0a, 0x0d, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x3e, 0x0a, 0x11, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x06, 0x74,
	0x69, 0x6d, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x68, 0x61,
	0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06,
	0x74, 0x69, 0x6d, 0x65, 0x72, 0x73, 0x22, 0xec, 0x01, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69, 0x72, 0x65, 0x5f, 0x61, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x69, 0x72, 0x65, 0x41, 0x74, 0x12, 0x3b,
	0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1f, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x3b, 0x0a, 0x0d, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x4a, 0x04, 0x08, 0x04, 0x10, 0x05, 0x4a, 0x04,
	0x08, 0x05, 0x10, 0x06, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x52, 0x09, 0x72, 0x6f, 0x6f, 0x6d,
	0x69, 0x65, 0x5f, 0x69, 0x64, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x4e, 0x75, 0x72, 0x50, 0x65, 0x63, 0x68, 0x2f, 0x68, 0x61, 0x6e, 0x6e,
	0x61, 0x68, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x6f, 0x3b, 0x68, 0x61, 0x6e, 0x6e,
	0x61, 0x68, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_timer_service_proto_rawDescOnce sync.Once
	file_timer_service_proto_rawDescData = file_timer_service_proto_rawDesc
)

func file_timer_service_proto_rawDescGZIP() []byte {
	file_timer_service_proto_rawDescOnce.Do(func() {
		file_timer_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_timer_service_proto_rawDescData)
	})
	return file_timer_service_proto_rawDescData
}

var file_timer_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_timer_service_proto_goTypes = []any{
	(*TimerCommand)(nil),      // 0: hannah.TimerCommand
	(*TimerReady)(nil),        // 1: hannah.TimerReady
	(*TimerNotReady)(nil),     // 2: hannah.TimerNotReady
	(*TimerCreate)(nil),       // 3: hannah.TimerCreate
	(*TimerCancel)(nil),       // 4: hannah.TimerCancel
	(*TimerListRequest)(nil),  // 5: hannah.TimerListRequest
	(*TimerMessage)(nil),      // 6: hannah.TimerMessage
	(*TimerAck)(nil),          // 7: hannah.TimerAck
	(*TimerFired)(nil),        // 8: hannah.TimerFired
	(*TimerListResponse)(nil), // 9: hannah.TimerListResponse
	(*TimerInfo)(nil),         // 10: hannah.TimerInfo
	nil,                       // 11: hannah.TimerCreate.MetadataEntry
	nil,                       // 12: hannah.TimerFired.MetadataEntry
	nil,                       // 13: hannah.TimerInfo.MetadataEntry
}
var file_timer_service_proto_depIdxs = []int32{
	3,  // 0: hannah.TimerCommand.create:type_name -> hannah.TimerCreate
	4,  // 1: hannah.TimerCommand.cancel:type_name -> hannah.TimerCancel
	5,  // 2: hannah.TimerCommand.list:type_name -> hannah.TimerListRequest
	1,  // 3: hannah.TimerCommand.ready:type_name -> hannah.TimerReady
	2,  // 4: hannah.TimerCommand.not_ready:type_name -> hannah.TimerNotReady
	11, // 5: hannah.TimerCreate.metadata:type_name -> hannah.TimerCreate.MetadataEntry
	7,  // 6: hannah.TimerMessage.ack:type_name -> hannah.TimerAck
	8,  // 7: hannah.TimerMessage.fired:type_name -> hannah.TimerFired
	9,  // 8: hannah.TimerMessage.list:type_name -> hannah.TimerListResponse
	12, // 9: hannah.TimerFired.metadata:type_name -> hannah.TimerFired.MetadataEntry
	10, // 10: hannah.TimerListResponse.timers:type_name -> hannah.TimerInfo
	13, // 11: hannah.TimerInfo.metadata:type_name -> hannah.TimerInfo.MetadataEntry
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_timer_service_proto_init() }
func file_timer_service_proto_init() {
	if File_timer_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_timer_service_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TimerCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timer_service_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*TimerReady); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timer_service_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*TimerNotReady); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timer_service_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*TimerCreate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timer_service_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*TimerCancel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timer_service_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*TimerListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timer_service_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*TimerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timer_service_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*TimerAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timer_service_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*TimerFired); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timer_service_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*TimerListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timer_service_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*TimerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_timer_service_proto_msgTypes[0].OneofWrappers = []any{
		(*TimerCommand_Create)(nil),
		(*TimerCommand_Cancel)(nil),
		(*TimerCommand_List)(nil),
		(*TimerCommand_Ready)(nil),
		(*TimerCommand_NotReady)(nil),
	}
	file_timer_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_timer_service_proto_msgTypes[6].OneofWrappers = []any{
		(*TimerMessage_Ack)(nil),
		(*TimerMessage_Fired)(nil),
		(*TimerMessage_List)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_timer_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_timer_service_proto_goTypes,
		DependencyIndexes: file_timer_service_proto_depIdxs,
		MessageInfos:      file_timer_service_proto_msgTypes,
	}.Build()
	File_timer_service_proto = out.File
	file_timer_service_proto_rawDesc = nil
	file_timer_service_proto_goTypes = nil
	file_timer_service_proto_depIdxs = nil
}
