// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: wakeword_capture.proto

package hannahproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SatelliteCaptureRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// "noise" (default) or "hey_hannah" — controls ESP streaming behaviour.
	// noise: continuous auto-flush every 5 s.
	// hey_hannah: stream only while PTT is held, flush on PTT release.
	SampleType string `protobuf:"bytes,2,opt,name=sample_type,json=sampleType,proto3" json:"sample_type,omitempty"`
}

func (x *SatelliteCaptureRequest) Reset() {
	*x = SatelliteCaptureRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wakeword_capture_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SatelliteCaptureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SatelliteCaptureRequest) ProtoMessage() {}

func (x *SatelliteCaptureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wakeword_capture_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SatelliteCaptureRequest.ProtoReflect.Descriptor instead.
func (*SatelliteCaptureRequest) Descriptor() ([]byte, []int) {
	return file_wakeword_capture_proto_rawDescGZIP(), []int{0}
}

func (x *SatelliteCaptureRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SatelliteCaptureRequest) GetSampleType() string {
	if x != nil {
		return x.SampleType
	}
	return ""
}

type TriggerPlinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId       string  `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	RecordDuration float32 `protobuf:"fixed32,2,opt,name=record_duration,json=recordDuration,proto3" json:"record_duration,omitempty"` // seconds to hold virtual PTT after plink (default 3.0)
}

func (x *TriggerPlinkRequest) Reset() {
	*x = TriggerPlinkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wakeword_capture_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TriggerPlinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerPlinkRequest) ProtoMessage() {}

func (x *TriggerPlinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wakeword_capture_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerPlinkRequest.ProtoReflect.Descriptor instead.
func (*TriggerPlinkRequest) Descriptor() ([]byte, []int) {
	return file_wakeword_capture_proto_rawDescGZIP(), []int{1}
}

func (x *TriggerPlinkRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *TriggerPlinkRequest) GetRecordDuration() float32 {
	if x != nil {
		return x.RecordDuration
	}
	return 0
}

// ok=false when the satellite is unknown or already captured by another client.
type SatelliteCaptureResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok    bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *SatelliteCaptureResponse) Reset() {
	*x = SatelliteCaptureResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wakeword_capture_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SatelliteCaptureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SatelliteCaptureResponse) ProtoMessage() {}

func (x *SatelliteCaptureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wakeword_capture_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SatelliteCaptureResponse.ProtoReflect.Descriptor instead.
func (*SatelliteCaptureResponse) Descriptor() ([]byte, []int) {
	return file_wakeword_capture_proto_rawDescGZIP(), []int{2}
}

func (x *SatelliteCaptureResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SatelliteCaptureResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// A single audio chunk streamed from a captured satellite to the collector.
// end_of_utterance=true marks a PTT-release boundary — the collector should
// finalise and save the accumulated audio as a labelled sample at that point.
type SatelliteAudioChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pcm            []byte `protobuf:"bytes,1,opt,name=pcm,proto3" json:"pcm,omitempty"`                                                // raw PCM, 16-bit signed mono
	SampleRate     int32  `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`               // Hz, typically 16000
	EndOfUtterance bool   `protobuf:"varint,3,opt,name=end_of_utterance,json=endOfUtterance,proto3" json:"end_of_utterance,omitempty"` // true = PTT released, utterance boundary
}

func (x *SatelliteAudioChunk) Reset() {
	*x = SatelliteAudioChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wakeword_capture_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SatelliteAudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SatelliteAudioChunk) ProtoMessage() {}

func (x *SatelliteAudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_wakeword_capture_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SatelliteAudioChunk.ProtoReflect.Descriptor instead.
func (*SatelliteAudioChunk) Descriptor() ([]byte, []int) {
	return file_wakeword_capture_proto_rawDescGZIP(), []int{3}
}

func (x *SatelliteAudioChunk) GetPcm() []byte {
	if x != nil {
		return x.Pcm
	}
	return nil
}

func (x *SatelliteAudioChunk) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *SatelliteAudioChunk) GetEndOfUtterance() bool {
	if x != nil {
		return x.EndOfUtterance
	}
	return false
}

var File_wakeword_capture_proto protoreflect.FileDescriptor

var file_wakeword_capture_proto_rawDesc = []byte{
	0x0a, 0x16, 0x77, 0x61, 0x6b, 0x65, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x63, 0x61, 0x70, 0x74, 0x75,
	0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68,
	0x22, 0x57, 0x0a, 0x17, 0x53, 0x61, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x74, 0x65, 0x43, 0x61, 0x70,
	0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x5b, 0x0a, 0x13, 0x54, 0x72, 0x69,
	0x67, 0x67, 0x65, 0x72, 0x50, 0x6c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x27, 0x0a,
	0x0f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x44, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x40, 0x0a, 0x18, 0x53, 0x61, 0x74, 0x65, 0x6c, 0x6c,
	0x69, 0x74, 0x65, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02,
	0x6f, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x72, 0x0a, 0x13, 0x53, 0x61, 0x74, 0x65,
	0x6c, 0x6c, 0x69, 0x74, 0x65, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12,
	0x10, 0x0a, 0x03, 0x70, 0x63, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x70, 0x63,
	0x6d, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x72, 0x61, 0x74, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x61,
	0x74, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x65, 0x6e, 0x64, 0x5f, 0x6f, 0x66, 0x5f, 0x75, 0x74, 0x74,
	0x65, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x65, 0x6e,
	0x64, 0x4f, 0x66, 0x55, 0x74, 0x74, 0x65, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x42, 0x30, 0x5a, 0x2e,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4e, 0x75, 0x72, 0x50, 0x65,
	0x63, 0x68, 0x2f, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d,
	0x67, 0x6f, 0x3b, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wakeword_capture_proto_rawDescOnce sync.Once
	file_wakeword_capture_proto_rawDescData = file_wakeword_capture_proto_rawDesc
)

func file_wakeword_capture_proto_rawDescGZIP() []byte {
	file_wakeword_capture_proto_rawDescOnce.Do(func() {
		file_wakeword_capture_proto_rawDescData = protoimpl.X.CompressGZIP(file_wakeword_capture_proto_rawDescData)
	})
	return file_wakeword_capture_proto_rawDescData
}

var file_wakeword_capture_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_wakeword_capture_proto_goTypes = []any{
	(*SatelliteCaptureRequest)(nil),  // 0: hannah.SatelliteCaptureRequest
	(*TriggerPlinkRequest)(nil),      // 1: hannah.TriggerPlinkRequest
	(*SatelliteCaptureResponse)(nil), // 2: hannah.SatelliteCaptureResponse
	(*SatelliteAudioChunk)(nil),      // 3: hannah.SatelliteAudioChunk
}
var file_wakeword_capture_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wakeword_capture_proto_init() }
func file_wakeword_capture_proto_init() {
	if File_wakeword_capture_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wakeword_capture_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SatelliteCaptureRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wakeword_capture_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*TriggerPlinkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wakeword_capture_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SatelliteCaptureResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wakeword_capture_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*SatelliteAudioChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wakeword_capture_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wakeword_capture_proto_goTypes,
		DependencyIndexes: file_wakeword_capture_proto_depIdxs,
		MessageInfos:      file_wakeword_capture_proto_msgTypes,
	}.Build()
	File_wakeword_capture_proto = out.File
	file_wakeword_capture_proto_rawDesc = nil
	file_wakeword_capture_proto_goTypes = nil
	file_wakeword_capture_proto_depIdxs = nil
}
