// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: hannah/v2/device_control_menu.proto

package hannahv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A device for control menus (WebUI, Telegram), in the typed device model: the class
// says what it is, the slots carry its current values and what can be controlled.
// Field numbers 3-8 are intentionally unused: the previous generation's DeviceInfo
// used them for state-based data with other types.
type DeviceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`     // TypedDevice.device_id
	Name        string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // display name, e.g. "DeckeSeite"
	DeviceClass DeviceClass `protobuf:"varint,10,opt,name=device_class,json=deviceClass,proto3,enum=hannah.v2.DeviceClass" json:"device_class,omitempty"`
	Slots       []*Slot     `protobuf:"bytes,11,rep,name=slots,proto3" json:"slots,omitempty"` // with current values; Slot.writable says what a menu may offer
	Available   bool        `protobuf:"varint,12,opt,name=available,proto3" json:"available,omitempty"`
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_v2_device_control_menu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_v2_device_control_menu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_hannah_v2_device_control_menu_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeviceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeviceInfo) GetDeviceClass() DeviceClass {
	if x != nil {
		return x.DeviceClass
	}
	return DeviceClass_DEVICE_CLASS_UNSPECIFIED
}

func (x *DeviceInfo) GetSlots() []*Slot {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *DeviceInfo) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

type RoomInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     string        `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`   // room_id (lowercase), e.g. "wohnzimmer"
	Name    string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // display name, e.g. "Wohnzimmer"
	Devices []*DeviceInfo `protobuf:"bytes,3,rep,name=devices,proto3" json:"devices,omitempty"`
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_v2_device_control_menu_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_v2_device_control_menu_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_hannah_v2_device_control_menu_proto_rawDescGZIP(), []int{1}
}

func (x *RoomInfo) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RoomInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomInfo) GetDevices() []*DeviceInfo {
	if x != nil {
		return x.Devices
	}
	return nil
}

type GetDevicesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rooms []*RoomInfo `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
}

func (x *GetDevicesResponse) Reset() {
	*x = GetDevicesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_v2_device_control_menu_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevicesResponse) ProtoMessage() {}

func (x *GetDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_v2_device_control_menu_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDevicesResponse.ProtoReflect.Descriptor instead.
func (*GetDevicesResponse) Descriptor() ([]byte, []int) {
	return file_hannah_v2_device_control_menu_proto_rawDescGZIP(), []int{2}
}

func (x *GetDevicesResponse) GetRooms() []*RoomInfo {
	if x != nil {
		return x.Rooms
	}
	return nil
}

// Direct control of one slot, bypassing the NLU.
type ControlDeviceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // DeviceInfo.id
	SlotId   string `protobuf:"bytes,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`       // Slot.slot_id, e.g. "on", "brightness"
	// The calling service and its user, same as SubmitTextRequest: Core looks up
	// the user via linked_accounts to check Slot.required_trust_level.
	// Unset or not linked = guest (trust level 0).
	SourceService string     `protobuf:"bytes,4,opt,name=source_service,json=sourceService,proto3" json:"source_service,omitempty"` // e.g. "telegram"
	SourceUserId  string     `protobuf:"bytes,5,opt,name=source_user_id,json=sourceUserId,proto3" json:"source_user_id,omitempty"`  // e.g. Telegram chat_id as string
	Value         *SlotValue `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`                                      // the value in the slot's documented scale (see SlotKind)
}

func (x *ControlDeviceRequest) Reset() {
	*x = ControlDeviceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_v2_device_control_menu_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControlDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlDeviceRequest) ProtoMessage() {}

func (x *ControlDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_v2_device_control_menu_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlDeviceRequest.ProtoReflect.Descriptor instead.
func (*ControlDeviceRequest) Descriptor() ([]byte, []int) {
	return file_hannah_v2_device_control_menu_proto_rawDescGZIP(), []int{3}
}

func (x *ControlDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ControlDeviceRequest) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *ControlDeviceRequest) GetSourceService() string {
	if x != nil {
		return x.SourceService
	}
	return ""
}

func (x *ControlDeviceRequest) GetSourceUserId() string {
	if x != nil {
		return x.SourceUserId
	}
	return ""
}

func (x *ControlDeviceRequest) GetValue() *SlotValue {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_hannah_v2_device_control_menu_proto protoreflect.FileDescriptor

var file_hannah_v2_device_control_menu_proto_rawDesc = []byte{
	0x0a, 0x23, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2f, 0x76, 0x32, 0x2f, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x6d, 0x65, 0x6e, 0x75, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x76, 0x32,
	0x1a, 0x1c, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2f, 0x76, 0x32, 0x2f, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb0,
	0x01, 0x0a, 0x0a, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x39, 0x0a, 0x0c, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x63, 0x6c, 0x61, 0x73,
	0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68,
	0x2e, 0x76, 0x32, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52,
	0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x25, 0x0a, 0x05,
	0x73, 0x6c, 0x6f, 0x74, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x68, 0x61,
	0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x76, 0x32, 0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x05, 0x73, 0x6c,
	0x6f, 0x74, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c,
	0x65, 0x22, 0x61, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x2f, 0x0a, 0x07, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x76, 0x32,
	0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x22, 0x3f, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x72, 0x6f,
	0x6f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x68, 0x61, 0x6e, 0x6e,
	0x61, 0x68, 0x2e, 0x76, 0x32, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05,
	0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x22, 0xc5, 0x01, 0x0a, 0x14, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73,
	0x6c, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6c,
	0x6f, 0x74, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x2a, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x76, 0x32, 0x2e, 0x53, 0x6c, 0x6f,
	0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x36, 0x5a,
	0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4e, 0x75, 0x72, 0x50,
	0x65, 0x63, 0x68, 0x2f, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2d, 0x67, 0x6f, 0x2f, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x76, 0x32, 0x3b, 0x68, 0x61, 0x6e,
	0x6e, 0x61, 0x68, 0x76, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hannah_v2_device_control_menu_proto_rawDescOnce sync.Once
	file_hannah_v2_device_control_menu_proto_rawDescData = file_hannah_v2_device_control_menu_proto_rawDesc
)

func file_hannah_v2_device_control_menu_proto_rawDescGZIP() []byte {
	file_hannah_v2_device_control_menu_proto_rawDescOnce.Do(func() {
		file_hannah_v2_device_control_menu_proto_rawDescData = protoimpl.X.CompressGZIP(file_hannah_v2_device_control_menu_proto_rawDescData)
	})
	return file_hannah_v2_device_control_menu_proto_rawDescData
}

var file_hannah_v2_device_control_menu_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_hannah_v2_device_control_menu_proto_goTypes = []any{
	(*DeviceInfo)(nil),           // 0: hannah.v2.DeviceInfo
	(*RoomInfo)(nil),             // 1: hannah.v2.RoomInfo
	(*GetDevicesResponse)(nil),   // 2: hannah.v2.GetDevicesResponse
	(*ControlDeviceRequest)(nil), // 3: hannah.v2.ControlDeviceRequest
	(DeviceClass)(0),             // 4: hannah.v2.DeviceClass
	(*Slot)(nil),                 // 5: hannah.v2.Slot
	(*SlotValue)(nil),            // 6: hannah.v2.SlotValue
}
var file_hannah_v2_device_control_menu_proto_depIdxs = []int32{
	4, // 0: hannah.v2.DeviceInfo.device_class:type_name -> hannah.v2.DeviceClass
	5, // 1: hannah.v2.DeviceInfo.slots:type_name -> hannah.v2.Slot
	0, // 2: hannah.v2.RoomInfo.devices:type_name -> hannah.v2.DeviceInfo
	1, // 3: hannah.v2.GetDevicesResponse.rooms:type_name -> hannah.v2.RoomInfo
	6, // 4: hannah.v2.ControlDeviceRequest.value:type_name -> hannah.v2.SlotValue
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_hannah_v2_device_control_menu_proto_init() }
func file_hannah_v2_device_control_menu_proto_init() {
	if File_hannah_v2_device_control_menu_proto != nil {
		return
	}
	file_hannah_v2_device_model_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_hannah_v2_device_control_menu_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*DeviceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_v2_device_control_menu_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*RoomInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_v2_device_control_menu_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetDevicesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_v2_device_control_menu_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ControlDeviceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hannah_v2_device_control_menu_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hannah_v2_device_control_menu_proto_goTypes,
		DependencyIndexes: file_hannah_v2_device_control_menu_proto_depIdxs,
		MessageInfos:      file_hannah_v2_device_control_menu_proto_msgTypes,
	}.Build()
	File_hannah_v2_device_control_menu_proto = out.File
	file_hannah_v2_device_control_menu_proto_rawDesc = nil
	file_hannah_v2_device_control_menu_proto_goTypes = nil
	file_hannah_v2_device_control_menu_proto_depIdxs = nil
}
