// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: hannah/v2/device_model.proto

package hannahv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// What kind of device this is. A class exists per family of verbs, not per feature:
// a measuring socket is a SOCKET with a filled POWER slot, not a class of its own.
type DeviceClass int32

const (
	DeviceClass_DEVICE_CLASS_UNSPECIFIED DeviceClass = 0
	// Switchable light. Slots: ON (required), BRIGHTNESS, COLOR, COLOR_TEMPERATURE.
	DeviceClass_DEVICE_CLASS_LIGHT DeviceClass = 1
	// Socket/plug. Slots: ON (required), POWER, ENERGY, VOLTAGE, CURRENT.
	DeviceClass_DEVICE_CLASS_SOCKET DeviceClass = 2
	// Any other switchable boolean that fits no other class (scene-like switches,
	// flags, vendor specific switches). Slots: ON (required).
	DeviceClass_DEVICE_CLASS_GENERIC_BINARY_SWITCH DeviceClass = 3
	// Thermostat/room climate. Slots: TARGET_TEMPERATURE (required), TEMPERATURE,
	// HUMIDITY, VALVE. Comfort/eco setpoints and similar are not slots.
	DeviceClass_DEVICE_CLASS_THERMOSTAT DeviceClass = 4
	// Blind, shutter, awning. Slots: POSITION (required), TILT, STOP.
	DeviceClass_DEVICE_CLASS_COVER DeviceClass = 5
	// Read-only measurements. At least one measurement slot: TEMPERATURE, HUMIDITY,
	// ILLUMINANCE, PRESSURE, CO2, IAQ, VOC, POWER, ENERGY, MOTION.
	DeviceClass_DEVICE_CLASS_SENSOR DeviceClass = 6
	// Door or window contact. Slots: OPEN (required, read-only).
	DeviceClass_DEVICE_CLASS_CONTACT DeviceClass = 7
	// Fallback for anything that matches no class: a list of typed values
	// (GENERIC_NUMBER / GENERIC_BOOL / GENERIC_TEXT), each with label and unit.
	DeviceClass_DEVICE_CLASS_GENERIC DeviceClass = 8
)

// Enum value maps for DeviceClass.
var (
	DeviceClass_name = map[int32]string{
		0: "DEVICE_CLASS_UNSPECIFIED",
		1: "DEVICE_CLASS_LIGHT",
		2: "DEVICE_CLASS_SOCKET",
		3: "DEVICE_CLASS_GENERIC_BINARY_SWITCH",
		4: "DEVICE_CLASS_THERMOSTAT",
		5: "DEVICE_CLASS_COVER",
		6: "DEVICE_CLASS_SENSOR",
		7: "DEVICE_CLASS_CONTACT",
		8: "DEVICE_CLASS_GENERIC",
	}
	DeviceClass_value = map[string]int32{
		"DEVICE_CLASS_UNSPECIFIED":           0,
		"DEVICE_CLASS_LIGHT":                 1,
		"DEVICE_CLASS_SOCKET":                2,
		"DEVICE_CLASS_GENERIC_BINARY_SWITCH": 3,
		"DEVICE_CLASS_THERMOSTAT":            4,
		"DEVICE_CLASS_COVER":                 5,
		"DEVICE_CLASS_SENSOR":                6,
		"DEVICE_CLASS_CONTACT":               7,
		"DEVICE_CLASS_GENERIC":               8,
	}
)

func (x DeviceClass) Enum() *DeviceClass {
	p := new(DeviceClass)
	*p = x
	return p
}

func (x DeviceClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceClass) Descriptor() protoreflect.EnumDescriptor {
	return file_hannah_v2_device_model_proto_enumTypes[0].Descriptor()
}

func (DeviceClass) Type() protoreflect.EnumType {
	return &file_hannah_v2_device_model_proto_enumTypes[0]
}

func (x DeviceClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceClass.Descriptor instead.
func (DeviceClass) EnumDescriptor() ([]byte, []int) {
	return file_hannah_v2_device_model_proto_rawDescGZIP(), []int{0}
}

// What a slot means, and therefore which scale and unit its value has. The adapter
// normalizes every value to exactly this scale; Core relies on it.
type SlotKind int32

const (
	SlotKind_SLOT_KIND_UNSPECIFIED SlotKind = 0
	// --- switching and light ---
	SlotKind_SLOT_KIND_ON                SlotKind = 1 // boolean: true = on
	SlotKind_SLOT_KIND_BRIGHTNESS        SlotKind = 2 // number, 0-100 (%)
	SlotKind_SLOT_KIND_COLOR             SlotKind = 3 // rgb, 0xRRGGBB
	SlotKind_SLOT_KIND_COLOR_TEMPERATURE SlotKind = 4 // number, Kelvin (e.g. 2700 warm white, 6500 cold white)
	// --- electricity ---
	SlotKind_SLOT_KIND_POWER   SlotKind = 10 // number, W
	SlotKind_SLOT_KIND_ENERGY  SlotKind = 11 // number, kWh (cumulative)
	SlotKind_SLOT_KIND_VOLTAGE SlotKind = 12 // number, V
	SlotKind_SLOT_KIND_CURRENT SlotKind = 13 // number, A
	// --- climate ---
	SlotKind_SLOT_KIND_TARGET_TEMPERATURE SlotKind = 20 // number, °C, writable setpoint
	SlotKind_SLOT_KIND_TEMPERATURE        SlotKind = 21 // number, °C, measured value
	SlotKind_SLOT_KIND_HUMIDITY           SlotKind = 22 // number, 0-100 (% relative)
	SlotKind_SLOT_KIND_VALVE              SlotKind = 23 // number, 0-100 (% open)
	// --- cover ---
	SlotKind_SLOT_KIND_POSITION SlotKind = 30 // number, 0-100 (%), 100 = open, 0 = closed (the adapter compensates inverted actuators)
	SlotKind_SLOT_KIND_TILT     SlotKind = 31 // number, 0-100 (%)
	SlotKind_SLOT_KIND_STOP     SlotKind = 32 // boolean trigger: true = stop movement, not a state
	// --- binary sensors ---
	SlotKind_SLOT_KIND_OPEN   SlotKind = 40 // boolean: true = open (door/window contact)
	SlotKind_SLOT_KIND_MOTION SlotKind = 41 // boolean: true = motion/presence detected
	// --- further measurements ---
	SlotKind_SLOT_KIND_ILLUMINANCE SlotKind = 50 // number, lux
	SlotKind_SLOT_KIND_PRESSURE    SlotKind = 51 // number, hPa
	SlotKind_SLOT_KIND_CO2         SlotKind = 52 // number, ppm
	SlotKind_SLOT_KIND_IAQ         SlotKind = 53 // number, index 0-500
	SlotKind_SLOT_KIND_VOC         SlotKind = 54 // number, ppm
	// --- generic values (DEVICE_CLASS_GENERIC), described by label and unit ---
	SlotKind_SLOT_KIND_GENERIC_NUMBER SlotKind = 90
	SlotKind_SLOT_KIND_GENERIC_BOOL   SlotKind = 91
	SlotKind_SLOT_KIND_GENERIC_TEXT   SlotKind = 92
)

// Enum value maps for SlotKind.
var (
	SlotKind_name = map[int32]string{
		0:  "SLOT_KIND_UNSPECIFIED",
		1:  "SLOT_KIND_ON",
		2:  "SLOT_KIND_BRIGHTNESS",
		3:  "SLOT_KIND_COLOR",
		4:  "SLOT_KIND_COLOR_TEMPERATURE",
		10: "SLOT_KIND_POWER",
		11: "SLOT_KIND_ENERGY",
		12: "SLOT_KIND_VOLTAGE",
		13: "SLOT_KIND_CURRENT",
		20: "SLOT_KIND_TARGET_TEMPERATURE",
		21: "SLOT_KIND_TEMPERATURE",
		22: "SLOT_KIND_HUMIDITY",
		23: "SLOT_KIND_VALVE",
		30: "SLOT_KIND_POSITION",
		31: "SLOT_KIND_TILT",
		32: "SLOT_KIND_STOP",
		40: "SLOT_KIND_OPEN",
		41: "SLOT_KIND_MOTION",
		50: "SLOT_KIND_ILLUMINANCE",
		51: "SLOT_KIND_PRESSURE",
		52: "SLOT_KIND_CO2",
		53: "SLOT_KIND_IAQ",
		54: "SLOT_KIND_VOC",
		90: "SLOT_KIND_GENERIC_NUMBER",
		91: "SLOT_KIND_GENERIC_BOOL",
		92: "SLOT_KIND_GENERIC_TEXT",
	}
	SlotKind_value = map[string]int32{
		"SLOT_KIND_UNSPECIFIED":        0,
		"SLOT_KIND_ON":                 1,
		"SLOT_KIND_BRIGHTNESS":         2,
		"SLOT_KIND_COLOR":              3,
		"SLOT_KIND_COLOR_TEMPERATURE":  4,
		"SLOT_KIND_POWER":              10,
		"SLOT_KIND_ENERGY":             11,
		"SLOT_KIND_VOLTAGE":            12,
		"SLOT_KIND_CURRENT":            13,
		"SLOT_KIND_TARGET_TEMPERATURE": 20,
		"SLOT_KIND_TEMPERATURE":        21,
		"SLOT_KIND_HUMIDITY":           22,
		"SLOT_KIND_VALVE":              23,
		"SLOT_KIND_POSITION":           30,
		"SLOT_KIND_TILT":               31,
		"SLOT_KIND_STOP":               32,
		"SLOT_KIND_OPEN":               40,
		"SLOT_KIND_MOTION":             41,
		"SLOT_KIND_ILLUMINANCE":        50,
		"SLOT_KIND_PRESSURE":           51,
		"SLOT_KIND_CO2":                52,
		"SLOT_KIND_IAQ":                53,
		"SLOT_KIND_VOC":                54,
		"SLOT_KIND_GENERIC_NUMBER":     90,
		"SLOT_KIND_GENERIC_BOOL":       91,
		"SLOT_KIND_GENERIC_TEXT":       92,
	}
)

func (x SlotKind) Enum() *SlotKind {
	p := new(SlotKind)
	*p = x
	return p
}

func (x SlotKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SlotKind) Descriptor() protoreflect.EnumDescriptor {
	return file_hannah_v2_device_model_proto_enumTypes[1].Descriptor()
}

func (SlotKind) Type() protoreflect.EnumType {
	return &file_hannah_v2_device_model_proto_enumTypes[1]
}

func (x SlotKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SlotKind.Descriptor instead.
func (SlotKind) EnumDescriptor() ([]byte, []int) {
	return file_hannah_v2_device_model_proto_rawDescGZIP(), []int{1}
}

// The value of a slot, typed. Which case is used follows from the SlotKind.
type SlotValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//	*SlotValue_Boolean
	//	*SlotValue_Number
	//	*SlotValue_Text
	//	*SlotValue_Rgb
	Value isSlotValue_Value `protobuf_oneof:"value"`
}

func (x *SlotValue) Reset() {
	*x = SlotValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_v2_device_model_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlotValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotValue) ProtoMessage() {}

func (x *SlotValue) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_v2_device_model_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotValue.ProtoReflect.Descriptor instead.
func (*SlotValue) Descriptor() ([]byte, []int) {
	return file_hannah_v2_device_model_proto_rawDescGZIP(), []int{0}
}

func (m *SlotValue) GetValue() isSlotValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *SlotValue) GetBoolean() bool {
	if x, ok := x.GetValue().(*SlotValue_Boolean); ok {
		return x.Boolean
	}
	return false
}

func (x *SlotValue) GetNumber() float64 {
	if x, ok := x.GetValue().(*SlotValue_Number); ok {
		return x.Number
	}
	return 0
}

func (x *SlotValue) GetText() string {
	if x, ok := x.GetValue().(*SlotValue_Text); ok {
		return x.Text
	}
	return ""
}

func (x *SlotValue) GetRgb() uint32 {
	if x, ok := x.GetValue().(*SlotValue_Rgb); ok {
		return x.Rgb
	}
	return 0
}

type isSlotValue_Value interface {
	isSlotValue_Value()
}

type SlotValue_Boolean struct {
	Boolean bool `protobuf:"varint,1,opt,name=boolean,proto3,oneof"`
}

type SlotValue_Number struct {
	Number float64 `protobuf:"fixed64,2,opt,name=number,proto3,oneof"`
}

type SlotValue_Text struct {
	Text string `protobuf:"bytes,3,opt,name=text,proto3,oneof"`
}

type SlotValue_Rgb struct {
	Rgb uint32 `protobuf:"varint,4,opt,name=rgb,proto3,oneof"` // 0xRRGGBB, used by SLOT_KIND_COLOR
}

func (*SlotValue_Boolean) isSlotValue_Value() {}

func (*SlotValue_Number) isSlotValue_Value() {}

func (*SlotValue_Text) isSlotValue_Value() {}

func (*SlotValue_Rgb) isSlotValue_Value() {}

// One capability of a device.
type Slot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Stable ID of this slot within its device, chosen by the adapter. For the standard
	// kinds the lowercase kind name without prefix ("on", "brightness", "target_temperature")
	// is recommended; it is what SlotUpdate and SetSlot address. GENERIC slots need it
	// because a device can carry several of the same kind.
	SlotId   string     `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	Kind     SlotKind   `protobuf:"varint,2,opt,name=kind,proto3,enum=hannah.v2.SlotKind" json:"kind,omitempty"`
	Value    *SlotValue `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`        // current value; unset = unknown
	Writable bool       `protobuf:"varint,4,opt,name=writable,proto3" json:"writable,omitempty"` // false = read-only (measurements, contacts)
	Unit     string     `protobuf:"bytes,5,opt,name=unit,proto3" json:"unit,omitempty"`          // informational, and for GENERIC slots; standard kinds have a fixed unit (see SlotKind)
	Label    string     `protobuf:"bytes,6,opt,name=label,proto3" json:"label,omitempty"`        // human-readable name, used by GENERIC slots
	// Minimum user trust level (0-10, same scale as the users' trust level) required to
	// control this slot, read by the adapter from common.custom["hannah.0"].neededTrust.
	// Unset = not configured, no restriction — distinct from an explicit 0.
	RequiredTrustLevel *int32 `protobuf:"varint,7,opt,name=required_trust_level,json=requiredTrustLevel,proto3,oneof" json:"required_trust_level,omitempty"`
}

func (x *Slot) Reset() {
	*x = Slot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_v2_device_model_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Slot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slot) ProtoMessage() {}

func (x *Slot) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_v2_device_model_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slot.ProtoReflect.Descriptor instead.
func (*Slot) Descriptor() ([]byte, []int) {
	return file_hannah_v2_device_model_proto_rawDescGZIP(), []int{1}
}

func (x *Slot) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *Slot) GetKind() SlotKind {
	if x != nil {
		return x.Kind
	}
	return SlotKind_SLOT_KIND_UNSPECIFIED
}

func (x *Slot) GetValue() *SlotValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Slot) GetWritable() bool {
	if x != nil {
		return x.Writable
	}
	return false
}

func (x *Slot) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Slot) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Slot) GetRequiredTrustLevel() int32 {
	if x != nil && x.RequiredTrustLevel != nil {
		return *x.RequiredTrustLevel
	}
	return 0
}

// A device, as the adapter derived it from the ioBroker objects (grouping, class, slots).
type TypedDevice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId    string      `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // stable ID of the device, chosen by the adapter; not an ioBroker state ID
	Name        string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                         // display name, mandatory
	Room        string      `protobuf:"bytes,3,opt,name=room,proto3" json:"room,omitempty"`                         // room_id (enum ID segment, see AgentRoom), mandatory
	Floor       string      `protobuf:"bytes,4,opt,name=floor,proto3" json:"floor,omitempty"`                       // floor, empty = none
	DeviceClass DeviceClass `protobuf:"varint,5,opt,name=device_class,json=deviceClass,proto3,enum=hannah.v2.DeviceClass" json:"device_class,omitempty"`
	Slots       []*Slot     `protobuf:"bytes,6,rep,name=slots,proto3" json:"slots,omitempty"`
	Available   bool        `protobuf:"varint,7,opt,name=available,proto3" json:"available,omitempty"` // false = device currently unreachable
}

func (x *TypedDevice) Reset() {
	*x = TypedDevice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_v2_device_model_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TypedDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypedDevice) ProtoMessage() {}

func (x *TypedDevice) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_v2_device_model_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypedDevice.ProtoReflect.Descriptor instead.
func (*TypedDevice) Descriptor() ([]byte, []int) {
	return file_hannah_v2_device_model_proto_rawDescGZIP(), []int{2}
}

func (x *TypedDevice) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *TypedDevice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TypedDevice) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *TypedDevice) GetFloor() string {
	if x != nil {
		return x.Floor
	}
	return ""
}

func (x *TypedDevice) GetDeviceClass() DeviceClass {
	if x != nil {
		return x.DeviceClass
	}
	return DeviceClass_DEVICE_CLASS_UNSPECIFIED
}

func (x *TypedDevice) GetSlots() []*Slot {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *TypedDevice) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

// All devices the adapter knows. Sent on AgentConnect and whenever the set of devices
// or their structure changes (devices added/removed, slots added/removed).
type TypedDeviceSnapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Devices []*TypedDevice `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
}

func (x *TypedDeviceSnapshot) Reset() {
	*x = TypedDeviceSnapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_v2_device_model_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TypedDeviceSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypedDeviceSnapshot) ProtoMessage() {}

func (x *TypedDeviceSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_v2_device_model_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypedDeviceSnapshot.ProtoReflect.Descriptor instead.
func (*TypedDeviceSnapshot) Descriptor() ([]byte, []int) {
	return file_hannah_v2_device_model_proto_rawDescGZIP(), []int{3}
}

func (x *TypedDeviceSnapshot) GetDevices() []*TypedDevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

// A slot changed. ack=true means the device confirmed the value (as opposed to the
// "desired" value), Hannah uses this to verify that a SetSlot was executed.
type SlotUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId string     `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	SlotId   string     `protobuf:"bytes,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	Value    *SlotValue `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Ack      bool       `protobuf:"varint,4,opt,name=ack,proto3" json:"ack,omitempty"`
	Ts       int64      `protobuf:"varint,5,opt,name=ts,proto3" json:"ts,omitempty"` // Unix timestamp in milliseconds
}

func (x *SlotUpdate) Reset() {
	*x = SlotUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_v2_device_model_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlotUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotUpdate) ProtoMessage() {}

func (x *SlotUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_v2_device_model_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotUpdate.ProtoReflect.Descriptor instead.
func (*SlotUpdate) Descriptor() ([]byte, []int) {
	return file_hannah_v2_device_model_proto_rawDescGZIP(), []int{4}
}

func (x *SlotUpdate) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SlotUpdate) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *SlotUpdate) GetValue() *SlotValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SlotUpdate) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

func (x *SlotUpdate) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

// A device became reachable or unreachable, without any of its slots changing.
type DeviceAvailability struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId  string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Available bool   `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
}

func (x *DeviceAvailability) Reset() {
	*x = DeviceAvailability{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_v2_device_model_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceAvailability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceAvailability) ProtoMessage() {}

func (x *DeviceAvailability) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_v2_device_model_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceAvailability.ProtoReflect.Descriptor instead.
func (*DeviceAvailability) Descriptor() ([]byte, []int) {
	return file_hannah_v2_device_model_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceAvailability) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceAvailability) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

// Hannah wants to control a slot. The adapter maps this onto the real state(s) and
// denormalizes the value; the confirmed result comes back as a SlotUpdate with ack=true.
type SetSlot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId string     `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	SlotId   string     `protobuf:"bytes,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	Value    *SlotValue `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SetSlot) Reset() {
	*x = SetSlot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hannah_v2_device_model_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSlot) ProtoMessage() {}

func (x *SetSlot) ProtoReflect() protoreflect.Message {
	mi := &file_hannah_v2_device_model_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSlot.ProtoReflect.Descriptor instead.
func (*SetSlot) Descriptor() ([]byte, []int) {
	return file_hannah_v2_device_model_proto_rawDescGZIP(), []int{6}
}

func (x *SetSlot) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SetSlot) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *SetSlot) GetValue() *SlotValue {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_hannah_v2_device_model_proto protoreflect.FileDescriptor

var file_hannah_v2_device_model_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2f, 0x76, 0x32, 0x2f, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09,
	0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x76, 0x32, 0x22, 0x74, 0x0a, 0x09, 0x53, 0x6c, 0x6f,
	0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1a, 0x0a, 0x07, 0x62, 0x6f, 0x6f, 0x6c, 0x65, 0x61,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x07, 0x62, 0x6f, 0x6f, 0x6c, 0x65,
	0x61, 0x6e, 0x12, 0x18, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x01, 0x48, 0x00, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x74, 0x65,
	0x78, 0x74, 0x12, 0x12, 0x0a, 0x03, 0x72, 0x67, 0x62, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x48,
	0x00, 0x52, 0x03, 0x72, 0x67, 0x62, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x8a, 0x02, 0x0a, 0x04, 0x53, 0x6c, 0x6f, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x6c, 0x6f, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49,
	0x64, 0x12, 0x27, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x13, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x76, 0x32, 0x2e, 0x53, 0x6c, 0x6f, 0x74,
	0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x2a, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x68, 0x61, 0x6e, 0x6e,
	0x61, 0x68, 0x2e, 0x76, 0x32, 0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x77, 0x72, 0x69, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x77, 0x72, 0x69, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x35, 0x0a, 0x14,
	0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x74, 0x72, 0x75, 0x73, 0x74, 0x5f, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x12, 0x72, 0x65,
	0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x54, 0x72, 0x75, 0x73, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x88, 0x01, 0x01, 0x42, 0x17, 0x0a, 0x15, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64,
	0x5f, 0x74, 0x72, 0x75, 0x73, 0x74, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0xe8, 0x01, 0x0a,
	0x0b, 0x54, 0x79, 0x70, 0x65, 0x64, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6f,
	0x6d, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x12, 0x39, 0x0a, 0x0c, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e,
	0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x76, 0x32, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6c, 0x61,
	0x73, 0x73, 0x12, 0x25, 0x0a, 0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x76, 0x32, 0x2e, 0x53, 0x6c,
	0x6f, 0x74, 0x52, 0x05, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x61, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x47, 0x0a, 0x13, 0x54, 0x79, 0x70, 0x65, 0x64,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x30,
	0x0a, 0x07, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x76, 0x32, 0x2e, 0x54, 0x79, 0x70, 0x65,
	0x64, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x07, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x22, 0x90, 0x01, 0x0a, 0x0a, 0x53, 0x6c, 0x6f, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x6c, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x76, 0x32,
	0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03,
	0x61, 0x63, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x74, 0x73, 0x22, 0x4f, 0x0a, 0x12, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x41, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61,
	0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x61, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x6c, 0x65, 0x22, 0x6b, 0x0a, 0x07, 0x53, 0x65, 0x74, 0x53, 0x6c, 0x6f, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x6c, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x2e, 0x76, 0x32,
	0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x2a, 0x86, 0x02, 0x0a, 0x0b, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x12, 0x1c, 0x0a, 0x18, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x43, 0x4c, 0x41, 0x53,
	0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x16, 0x0a, 0x12, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x43, 0x4c, 0x41, 0x53, 0x53, 0x5f,
	0x4c, 0x49, 0x47, 0x48, 0x54, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x44, 0x45, 0x56, 0x49, 0x43,
	0x45, 0x5f, 0x43, 0x4c, 0x41, 0x53, 0x53, 0x5f, 0x53, 0x4f, 0x43, 0x4b, 0x45, 0x54, 0x10, 0x02,
	0x12, 0x26, 0x0a, 0x22, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x43, 0x4c, 0x41, 0x53, 0x53,
	0x5f, 0x47, 0x45, 0x4e, 0x45, 0x52, 0x49, 0x43, 0x5f, 0x42, 0x49, 0x4e, 0x41, 0x52, 0x59, 0x5f,
	0x53, 0x57, 0x49, 0x54, 0x43, 0x48, 0x10, 0x03, 0x12, 0x1b, 0x0a, 0x17, 0x44, 0x45, 0x56, 0x49,
	0x43, 0x45, 0x5f, 0x43, 0x4c, 0x41, 0x53, 0x53, 0x5f, 0x54, 0x48, 0x45, 0x52, 0x4d, 0x4f, 0x53,
	0x54, 0x41, 0x54, 0x10, 0x04, 0x12, 0x16, 0x0a, 0x12, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f,
	0x43, 0x4c, 0x41, 0x53, 0x53, 0x5f, 0x43, 0x4f, 0x56, 0x45, 0x52, 0x10, 0x05, 0x12, 0x17, 0x0a,
	0x13, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x43, 0x4c, 0x41, 0x53, 0x53, 0x5f, 0x53, 0x45,
	0x4e, 0x53, 0x4f, 0x52, 0x10, 0x06, 0x12, 0x18, 0x0a, 0x14, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45,
	0x5f, 0x43, 0x4c, 0x41, 0x53, 0x53, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x41, 0x43, 0x54, 0x10, 0x07,
	0x12, 0x18, 0x0a, 0x14, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x43, 0x4c, 0x41, 0x53, 0x53,
	0x5f, 0x47, 0x45, 0x4e, 0x45, 0x52, 0x49, 0x43, 0x10, 0x08, 0x2a, 0xf6, 0x04, 0x0a, 0x08, 0x53,
	0x6c, 0x6f, 0x74, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x19, 0x0a, 0x15, 0x53, 0x4c, 0x4f, 0x54, 0x5f,
	0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x4c, 0x4f, 0x54, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f,
	0x4f, 0x4e, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x53, 0x4c, 0x4f, 0x54, 0x5f, 0x4b, 0x49, 0x4e,
	0x44, 0x5f, 0x42, 0x52, 0x49, 0x47, 0x48, 0x54, 0x4e, 0x45, 0x53, 0x53, 0x10, 0x02, 0x12, 0x13,
	0x0a, 0x0f, 0x53, 0x4c, 0x4f, 0x54, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x43, 0x4f, 0x4c, 0x4f,
	0x52, 0x10, 0x03, 0x12, 0x1f, 0x0a, 0x1b, 0x53, 0x4c, 0x4f, 0x54, 0x5f, 0x4b, 0x49, 0x4e, 0x44,
	0x5f, 0x43, 0x4f, 0x4c, 0x4f, 0x52, 0x5f, 0x54, 0x45, 0x4d, 0x50, 0x45, 0x52, 0x41, 0x54, 0x55,
	0x52, 0x45, 0x10, 0x04, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x4c, 0x4f, 0x54, 0x5f, 0x4b, 0x49, 0x4e,
	0x44, 0x5f, 0x50, 0x4f, 0x57, 0x45, 0x52, 0x10, 0x0a, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x4c, 0x4f,
	0x54, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x45, 0x4e, 0x45, 0x52, 0x47, 0x59, 0x10, 0x0b, 0x12,
	0x15, 0x0a, 0x11, 0x53, 0x4c, 0x4f, 0x54, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x56, 0x4f, 0x4c,
	0x54, 0x41, 0x47, 0x45, 0x10, 0x0c, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x4c, 0x4f, 0x54, 0x5f, 0x4b,
	0x49, 0x4e, 0x44, 0x5f, 0x43, 0x55, 0x52, 0x52, 0x45, 0x4e, 0x54, 0x10, 0x0d, 0x12, 0x20, 0x0a,
	0x1c, 0x53, 0x4c, 0x4f, 0x54, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x54, 0x41, 0x52, 0x47, 0x45,
	0x54, 0x5f, 0x54, 0x45, 0x4d, 0x50, 0x45, 0x52, 0x41, 0x54, 0x55, 0x52, 0x45, 0x10, 0x14, 0x12,
	0x19, 0x0a, 0x15, 0x53, 0x4c, 0x4f, 0x54, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x54, 0x45, 0x4d,
	0x50, 0x45, 0x52, 0x41, 0x54, 0x55, 0x52, 0x45, 0x10, 0x15, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x4c,
	0x4f, 0x54, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x48, 0x55, 0x4d, 0x49, 0x44, 0x49, 0x54, 0x59,
	0x10, 0x16, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x4c, 0x4f, 0x54, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f,
	0x56, 0x41, 0x4c, 0x56, 0x45, 0x10, 0x17, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x4c, 0x4f, 0x54, 0x5f,
	0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x50, 0x4f, 0x53, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x1e, 0x12,
	0x12, 0x0a, 0x0e, 0x53, 0x4c, 0x4f, 0x54, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x54, 0x49, 0x4c,
	0x54, 0x10, 0x1f, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x4c, 0x4f, 0x54, 0x5f, 0x4b, 0x49, 0x4e, 0x44,
	0x5f, 0x53, 0x54, 0x4f, 0x50, 0x10, 0x20, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x4c, 0x4f, 0x54, 0x5f,
	0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x4f, 0x50, 0x45, 0x4e, 0x10, 0x28, 0x12, 0x14, 0x0a, 0x10, 0x53,
	0x4c, 0x4f, 0x54, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x4d, 0x4f, 0x54, 0x49, 0x4f, 0x4e, 0x10,
	0x29, 0x12, 0x19, 0x0a, 0x15, 0x53, 0x4c, 0x4f, 0x54, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x49,
	0x4c, 0x4c, 0x55, 0x4d, 0x49, 0x4e, 0x41, 0x4e, 0x43, 0x45, 0x10, 0x32, 0x12, 0x16, 0x0a, 0x12,
	0x53, 0x4c, 0x4f, 0x54, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x50, 0x52, 0x45, 0x53, 0x53, 0x55,
	0x52, 0x45, 0x10, 0x33, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x4c, 0x4f, 0x54, 0x5f, 0x4b, 0x49, 0x4e,
	0x44, 0x5f, 0x43, 0x4f, 0x32, 0x10, 0x34, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x4c, 0x4f, 0x54, 0x5f,
	0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x49, 0x41, 0x51, 0x10, 0x35, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x4c,
	0x4f, 0x54, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x56, 0x4f, 0x43, 0x10, 0x36, 0x12, 0x1c, 0x0a,
	0x18, 0x53, 0x4c, 0x4f, 0x54, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x47, 0x45, 0x4e, 0x45, 0x52,
	0x49, 0x43, 0x5f, 0x4e, 0x55, 0x4d, 0x42, 0x45, 0x52, 0x10, 0x5a, 0x12, 0x1a, 0x0a, 0x16, 0x53,
	0x4c, 0x4f, 0x54, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x47, 0x45, 0x4e, 0x45, 0x52, 0x49, 0x43,
	0x5f, 0x42, 0x4f, 0x4f, 0x4c, 0x10, 0x5b, 0x12, 0x1a, 0x0a, 0x16, 0x53, 0x4c, 0x4f, 0x54, 0x5f,
	0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x47, 0x45, 0x4e, 0x45, 0x52, 0x49, 0x43, 0x5f, 0x54, 0x45, 0x58,
	0x54, 0x10, 0x5c, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x4e, 0x75, 0x72, 0x50, 0x65, 0x63, 0x68, 0x2f, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68,
	0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x6f, 0x2f, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68,
	0x76, 0x32, 0x3b, 0x68, 0x61, 0x6e, 0x6e, 0x61, 0x68, 0x76, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_hannah_v2_device_model_proto_rawDescOnce sync.Once
	file_hannah_v2_device_model_proto_rawDescData = file_hannah_v2_device_model_proto_rawDesc
)

func file_hannah_v2_device_model_proto_rawDescGZIP() []byte {
	file_hannah_v2_device_model_proto_rawDescOnce.Do(func() {
		file_hannah_v2_device_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_hannah_v2_device_model_proto_rawDescData)
	})
	return file_hannah_v2_device_model_proto_rawDescData
}

var file_hannah_v2_device_model_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_hannah_v2_device_model_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_hannah_v2_device_model_proto_goTypes = []any{
	(DeviceClass)(0),            // 0: hannah.v2.DeviceClass
	(SlotKind)(0),               // 1: hannah.v2.SlotKind
	(*SlotValue)(nil),           // 2: hannah.v2.SlotValue
	(*Slot)(nil),                // 3: hannah.v2.Slot
	(*TypedDevice)(nil),         // 4: hannah.v2.TypedDevice
	(*TypedDeviceSnapshot)(nil), // 5: hannah.v2.TypedDeviceSnapshot
	(*SlotUpdate)(nil),          // 6: hannah.v2.SlotUpdate
	(*DeviceAvailability)(nil),  // 7: hannah.v2.DeviceAvailability
	(*SetSlot)(nil),             // 8: hannah.v2.SetSlot
}
var file_hannah_v2_device_model_proto_depIdxs = []int32{
	1, // 0: hannah.v2.Slot.kind:type_name -> hannah.v2.SlotKind
	2, // 1: hannah.v2.Slot.value:type_name -> hannah.v2.SlotValue
	0, // 2: hannah.v2.TypedDevice.device_class:type_name -> hannah.v2.DeviceClass
	3, // 3: hannah.v2.TypedDevice.slots:type_name -> hannah.v2.Slot
	4, // 4: hannah.v2.TypedDeviceSnapshot.devices:type_name -> hannah.v2.TypedDevice
	2, // 5: hannah.v2.SlotUpdate.value:type_name -> hannah.v2.SlotValue
	2, // 6: hannah.v2.SetSlot.value:type_name -> hannah.v2.SlotValue
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_hannah_v2_device_model_proto_init() }
func file_hannah_v2_device_model_proto_init() {
	if File_hannah_v2_device_model_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hannah_v2_device_model_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SlotValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_v2_device_model_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Slot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_v2_device_model_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*TypedDevice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_v2_device_model_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*TypedDeviceSnapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_v2_device_model_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*SlotUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_v2_device_model_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DeviceAvailability); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hannah_v2_device_model_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*SetSlot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_hannah_v2_device_model_proto_msgTypes[0].OneofWrappers = []any{
		(*SlotValue_Boolean)(nil),
		(*SlotValue_Number)(nil),
		(*SlotValue_Text)(nil),
		(*SlotValue_Rgb)(nil),
	}
	file_hannah_v2_device_model_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hannah_v2_device_model_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hannah_v2_device_model_proto_goTypes,
		DependencyIndexes: file_hannah_v2_device_model_proto_depIdxs,
		EnumInfos:         file_hannah_v2_device_model_proto_enumTypes,
		MessageInfos:      file_hannah_v2_device_model_proto_msgTypes,
	}.Build()
	File_hannah_v2_device_model_proto = out.File
	file_hannah_v2_device_model_proto_rawDesc = nil
	file_hannah_v2_device_model_proto_goTypes = nil
	file_hannah_v2_device_model_proto_depIdxs = nil
}
